### ISSUE TITLE
amqp protocol support

### ISSUE THREAD

**Issue by hassanbakerrts** [grafana/k6#1073]
I'm trying to connect to rabbitmq using the framework `[rhea](https://github.com/amqp/rhea)` so I used `browserify` to make the framework compatible. However, the resulted js is constantly throwing errors. Is there any work-around for this issue?

**Comment by na--** [comment]
Such a library won't work through browserify, since it makes network connections that can't be polyfilled - k6 is neither a browser, nor a node.js clone.

In the future we'll probably add support for such protocols directly in k6, but I can't give even a rough estimation when that will be, sorry. Event loops (https://github.com/loadimpact/k6/issues/882) are very likely a prerequisite though...

**Comment by olegbespalov** [comment]
Currently, adding amqp support to the core is outside our roadmap. There is an extension https://github.com/grafana/xk6-amqp exists, but unfortunately, it is also not under development.
