### ISSUE TITLE
URL scheme warning for `//process`

### ISSUE THREAD

**Issue by nicodn** [grafana/k6#1129]
I'm seeing some odd warning messages on startup:

```
time="2019-08-28T14:21:35-04:00" level=warning msg="A url was resolved but it didn't have scheme. This will be deprecated in the future and all remote modules will need to explicitly use `https` as scheme" url=//process
```

I'm not sure where this is coming from.

**Comment by na--** [comment]
@nicodn, though this might be a dupe of #1126, can you share what triggered the problem in your case? We're suspect that this is some sort of an issue with [goja](https://github.com/dop251/goja), the JS runtime k6 uses, but we couldn't construct a simple example that demonstrates the problem so that we can easily debug it and/or report it upstream. Any other instances of the same issue would be very helpful!

**Comment by nicodn** [comment]
I was sharing some js libraries between load testing tools so had something like this:
```
let process;
try {
    process = require('process');
} catch (err) { } //pass

if ((process && process.env.VARIABLE == "true") ||
    (typeof __ENV !== 'undefined' && __ENV.VARIABLE && __ENV.VARIABLE == "true")) {
    SOMETHING = false;
} else SOMETHING = true;
```

**Comment by na--** [comment]
Ah, then this isn't really a `duplicate`, but it's also not really a `bug`... Rather it's mostly working as intended :smile: What happens is that because k6 isn't node.js, we don't have a `process` module and instead try to resolve it like the obsolete URL imports we supported (i.e. `import jslib.k6.io/some_url_without_a_schema`) and that obviously fails.
