### ISSUE TITLE
Obey cache directives

### ISSUE THREAD

**Issue by micsjo** [grafana/k6#142]
As we keep VU state per VU between iterations it should be possible to implement an _option_ that controls if we ignore cache directives or obey them in subsequent iterations.

The most common cache paradigm in performance testing is to ignore caching. This is usually not corresponding to real world usage as a lot of users will be returning and thus have items client cached.

The most common solution for this is sometimes to implement cache requests (expecting 304 Not Modified responses) _by hand coding_ requests to ask for new versions of cached data. This is _very_ time consuming and requires multiple versions of identical script code to be executed.

The _preferred_ solution is to allow the execution to control cache behavior. I.e. an _option_ to set if we shall obey cache in subsequent iterations or if we shall ignore it.

**Comment by ragnarlonn** [comment]
Yeah, I thought about this also recently, when I wrote the Pantheon ecommerce script example. There, I wanted to simulate the effects of caching and ended up having to write a lot of extra code to get a traffic pattern that was at least close to what a real browser would exhibit. Would have been great if k6 could interpret Cache-control etc headers and remember which data has already been retrieved, then add If-Modified-Since headers to requests. 

So - would be an excellent feature for website testing, but probably not trivial to design the API so it becomes user-friendly. Setting an option to enable automatic cache handling sounds good, but does that mean people have to check for 304's *and* for 200's to determine whether a request was successful or not?  And what if they want to verify the body content of a 304 response? I think we need to figure out what a script sample would look like with auto-caching.

**Comment by micsjo** [comment]
Checking for content will always have the same content (it's cached) so that's not an issue.

Checking for _specific_ response codes requires you to know what you are doing - this is not a problem either. And I have a very hard time understanding the actual use case to check for a 200 response?

**Comment by micsjo** [comment]
Oh, and caching does not only rely on the If-Modified-Since, it also makes use of ETags and sometimes other bits and bobs.

**Comment by ragnarlonn** [comment]
You never check for 200-response?  What kinds of checks/validations do you usually do?

About content, I wasn't sure whether it would be intuitive to auto-populate res.body with previously fetched content, when you get a 304 response. The *actual* body content of the HTTP transaction is, after all, empty. In the unlikely case someone wants to e.g. use k6 to test an HTTP server application of some kind, and make sure it returns empty bodies with 304 responses, that would not be possible if we behave like a browser executing JS code from a webpage. I.e. we hide the workings of HTTP from k6. You're probably right that we want to do this in order to make life simpler for the vast majority of testers, but it is worth considering the effects.

**Comment by micsjo** [comment]
Rephrase: I have a very hard time understanding the actual use case to check _manually_ for a 200 response?

It will _fail_ for everything >= 400 and if I do something with the results (like analyzing them) I will see all the results including responses.

**Comment by uppfinnarn** [comment]
I think what @ragnarlonn is saying is that this would fail on the second iteration?

```js
check(http.get("http://example.com/", { cache: true }), {
    "status is 200": (r) => r.status === 200,
});
```

It'd make much more sense to just handle cached responses transparently, eg. return status 200 for a cached 200 response.

**Comment by micsjo** [comment]
Yes, I understand it will fail with a 304 response. What _I_ fail to understand is why it is meaningful to have a manual check for 200 status in this case?

I don't think it's a good idea to return 200 OK when we get a 304 in reality. Tell it like it is. Or that is not what you meant?

**Comment by ragnarlonn** [comment]
I also think returning the true response code is better - if we have to choose (we could return both). If we provide the true response code it means people can choose to handle redirects themselves, rather than have them happen automatically, and I think that is a plus. Sometimes you want to debug a complicated redirect sequence and then it can help being able to handle redirects yourself rather than having them done automatically. But @micsjo - if we want to "tell it like it is", should we put a previously fetched HTTP body into an HTTP response object when we encounter a 304 response? I think this is a matter of whether we see the response object as providing information about an actual HTTP transaction, or if it is information about the HTTP resource being requested. I'd vote to make it info about the transaction, because that is what most testing tools and APIs do. But I have a bit of a networking background OTOH; web developers may think differently here?

**Comment by micsjo** [comment]
Reading up a bit more on how other tools enable this type of behavior it's different. Some don't at all, some try to act like browsers.

So to open a can of worms here...

**Retaining _context_ for VUs across iterations would mean "act like a browser"**

- keep cookies
- keep cached content
- obey caching directives (meaning do not even ask for client cached content! just use it)
- if caching rules say to ask for a newer version (If-Modified-Since + possibly ETag) do so (which will return new content _or_ a 304 response

The most granular settings I can find also allows to configure specifically the behavior for keeping the cached content. The default being - keep it. Why? It can be used for validating, dynamic content etc so it's needed. If that is not possible we need some way to keep data in a VU context from the script (sort of like memcache for individual VUs). It's possible to turn off because it can consume a lot of memory.

**Comment by uppfinnarn** [comment]
Oh dear, that **is** a can of worms…

My spontaneous reaction is that this would change the behavior of the tool in a way that may not be desirable, eg. instead of simulating, say, 1000 *concurrent* users, we'd be simulating 1000 users that keep navigating around on your site, returning over and over. While such a dedicated userbase is a dream for many a site, I don't know if it would generate the data people are looking for.

What if though: we obey cache directives within the same iteration, similar to how we treat cookies right now?

**Comment by bagder** [comment]
Let me add some complexity: a recent development in the HTTP world is the problem that just *refreshing* the state even if you have a (complicated) page fully cached is also very time consuming so there's now a [Cache-Control: immutable](https://tools.ietf.org/html/draft-mcmanus-immutable-01) header being proposed (in use by Facebook among others, supported by at least Firefox) which basically tell the browser to *never* reload that resource. So if you wanted to test 1000 users reloading the Facebook page like a modern browser would, said resources should not get reloaded...

**Comment by micsjo** [comment]
Within the same iteration would be a very good implementation (preferably with some on/off option).

**Comment by saurabhvyas9** [comment]
Considering there has been no response from quite some time, 
Is browser caching or context implemented or supported by K6 now for VUs ?

**Comment by na--** [comment]
No, sorry. This is currently not on the k6 roadmap, and it's definitely a big can of worms. But I think everything caching-related can be implemented as a stateful wrapper around the k6 `http` module that is written in pure JavaScript, with no changes to the k6 Go code. Then it can be deployed on a per-VU or per-iteration basis, whatever is appropriate for the specific use case. So if anyone is interested in working on that and produces something that's of reasonable quality, I think we can semi-officially endorse it.

**Comment by olegbespalov** [comment]
The team decided to close the issue as not planned.

If we have the capacity and see interest in such functionality in the future, we could consider re-opening it.
