### ISSUE TITLE
Improve gRPC connection state management

### ISSUE THREAD

**Issue by na--** [grafana/k6#1808]
https://community.k6.io/t/reconnect-in-grpc/1286 is a good example of how our gRPC implementation is not very flexible yet. Specifically, we don't have a good way to detect client disconnects. And I don't have a good idea how to handle them well, though something event-based seems reasonable, so we might need to implement https://github.com/loadimpact/k6/issues/882 before we can...

**Comment by codebien** [comment]
I'm closing as this issue seems unlikely to be resolved.
If the client disconnects then I expect a re-run of the test will be required. The cases where the user wants to test the client disconnecting sound minor. And, in any case, with a bit of effort, the goal is still achievable by using the [StatusDeadlineExceeded](https://grafana.com/docs/k6/latest/javascript-api/k6-net-grpc/constants/) code as proved on the forum. 

The current logic using the status code as proposed on the forum seems enough. We may re-evaluate the decision in the future if we find a higher demand.
