### ISSUE TITLE
RSocket Support

### ISSUE THREAD

**Issue by emax19** [grafana/k6#1859]
The RSocket technology has burst into the IT market. It's a very promising technology already used by many big products. So, it will be very helpful to start to support that, please take a look.

**Comment by na--** [comment]
Thanks for making this issue! If anyone else is interested, feel free to give :+1: to the post above. FWIW, this is the first time I'm hearing about RSocket and it seems interesting, though I doubt it has very wide adoption yet.

At some future point, we _might_ add support for RSocket in the k6 core, but for the foreseeable future, an xk6 extension would probably be a better fit. There seems to be at least one Go library for it (https://github.com/rsocket/rsocket-go), so here are some links with details about xk6:
- https://github.com/k6io/xk6
- https://k6.io/blog/extending-k6-with-xk6

The only caution here is that k6 doesn't yet have native event loops in every VU, and I imagine RSocket support would be a bit more synchronous because of it. Follow https://github.com/loadimpact/k6/issues/882 for updates on the topic.

**Comment by mstoykov** [comment]
As there are currently no plans for RSocket to become part of the k6 core and it doesn't seem like it might in the future I am closing this issue.

As mentioned in the previous comment this likely should be an extension. I did try to find if someone has made one, but unsuccesfully :(.
