### ISSUE TITLE
K6 - open source - InfluxDB shows errors when there is none on k6 console

### ISSUE THREAD

**Issue by voarsh2** [grafana/k6#1985]
## Environment

- k6 version:k6 v0.31.1 (2021-03-17T13:23:23+0000/e9d8349, go1.15.8, linux/amd64) 
- OS and version: Ubuntu 20.4
- Docker version and image, if applicable: 

## Expected Behavior

Running K6 and having http_req_failed at anything other than 0 should properly send it to InfluxDB. I am using 1.8.
Using these dashboards: https://k6.io/docs/results-visualization/influxdb-+-grafana/
(Some of them even show the wrong number of virtual users, but anyway, none of them actually show the failed requests count, at all.

## Actual Behavior
Can see requests, user count (in some dashboards correctly, but none of them show any data for failed requests, console does (on k6 itself)

**Comment by voarsh2** [comment]
Closing, as it needed http_req_failed in dashboard

**Comment by voarsh2** [comment]
Reopening- as I ran tests with the dashboard fixed:
I see:
http_req_failed................: 0.00%  ✓ 0

But InfluxDB shows:
![image](https://user-images.githubusercontent.com/60437695/115765016-23759200-a39e-11eb-931c-bfba0b390ee1.png)

**Comment by voarsh2** [comment]
I changed error code to need to be 503 - that's a guaranteed error code for my project.
But, I don't things are quite right about this behaviour?

**Comment by MStoykov** [comment]
Hi @voarsh2, can you please provide what are your influxdb's queries and what is the output in the cli that makes you think there is a discrepancy.

From this graph I made it looks like it is working as expected 
![image](https://user-images.githubusercontent.com/312246/115831990-0206bb80-a41b-11eb-967f-da3149c29c60.png)

As you can see `http_req_failed` needs to be graphed specially as it is a Rate as explained [here](https://community.k6.io/t/plot-http-req-failed/1647/2?u=mstoykov). The other two graphs are all the requests and the requests that have status code !=200, which in my case will make them failed ones ... as you can see the failed and the !=200 requests are the same. I even graphed one of them mirrored so it is easier to see (as they otherwise overlap).

**Comment by na--** [comment]
Closing this due to age and lack of response. We can reopen it if the original author (or someone with a similar issue) replies.
