### ISSUE TITLE
Improve Homebrew build

### ISSUE THREAD

**Issue by imiric** [grafana/k6#1997]
The current [k6 Homebrew formula](https://github.com/Homebrew/homebrew-core/blob/b5ed3990790c91e3fe6275133cabd63e0a8aae1b/Formula/k6.rb) doesn't set any of the build flags we use in [`build-release.sh`](https://github.com/k6io/k6/blob/14c6cd9f0a8e1923a1dc8aebf304bbeffd58581e/build-release.sh) like `-trimpath` or `-ldflags` to inject the build date and Git commit, so the `k6 version` output for the Homebrew binary is e.g. `k6 v0.31.1 ((devel), go1.16.2, darwin/amd64)`. This should be consistent with how `build-release.sh` works, which generates a version string like `k6 v0.31.1 (2021-03-17T13:23:23+0000/e9d8349, go1.15.8, linux/amd64)`, while also keeping in mind #1996.

**Comment by joanlopez** [comment]
Double-checked, with the latest release (v0.50.0):

- On MacOS, installed with Homebrew: `k6 v0.50.0 (go1.22.1, darwin/arm64)` 
- On MacOS, using the binary from GitHub Releases: `k6 v0.50.0 (commit/f18209a5e3, go1.21.8, darwin/arm64)` 
- On MacOS, using the Docker container: `k6 v0.50.0 (commit/f18209a5e3, go1.21.8, linux/arm64)`
- On a Debian container, [following installation steps](https://k6.io/docs/get-started/installation/): `k6 v0.50.0 (commit/f18209a5e3, go1.21.8, linux/amd64)`

So, yeah, for the sake of consistency, we should adjust the Homebrew build. Let's give it a try!

**Comment by joanlopez** [comment]
After an internal discussion with the team, we decided to close this issue as it's no longer such a problem as it was exposed at the initial description of the issue, where the build _seemed_ to be a development one.

Also considering that:
- The k6 version (e.g. `v0.50.0`, without the commit hash) should be enough in the vast majority of cases when debugging bugs or doing things like that.
- The way k6 is being built now for Homebrew: running `go build` over the release source code, instead of, for instance, pulling the binaries from GH releases, seems to be the convention in Homebrew.

So, with that being said, we decided to close this for now. If anybody finds this issue, and have any meaningful argument in favor of putting some efforts to make `k6 version` outputs look the same, please share. Likewise, if we ever re-consider this more important, we may want to explore a solution. For now, it just doesn't deserves the effort.

Thanks! 🙇🏻
