### ISSUE TITLE
Harmonize blocklist, blacklist and whitelist options

### ISSUE THREAD

**Issue by simskij** [grafana/k6#2059]
We currently have both blocklist for hostnames and a black- and whitelist for IPs. It would probably make sense to harmonize these, and maybe even reduce them to only block and allow, given that they serve somewhat the same purpose. Mixing IPs and hostname expressions in the same arrays sounds like it would be a more reasonable behavior than having to remember all four options.

**Comment by na--** [comment]
Hmm IP and hostname blocking work very differently in the codebase, one happens after and the other before DNS resolution. Though if we had thought to combine them in a single option when we added hostname blocking [in v0.29.0](https://github.com/k6io/k6/blob/master/release%20notes/v0.29.0.md#new-option-for-blocking-hostnames-1666), we probably could have done it by just trying to parse everything as an IP and split IPs and hostnames at config time... :disappointed: 

Now doing this will be quite a bit more complicated because of https://github.com/loadimpact/k6/issues/883
