### ISSUE TITLE
Accept FileData type for http.post body

### ISSUE THREAD

**Issue by codebien** [grafana/k6#2095]
## Feature Description

Currently, the `http.post` method doesn't accept a body parameter using a FileData type. As [the documentation](https://k6.io/docs/examples/data-uploads/#multipart-request-uploading-a-file) is mentioning it just supports a FileData type when it's part of an object as a property that doesn't seem the best UX.

Originally requested from 

## Suggested Solution

Add implementation to accept a FileData type directly as a body parameter.

**Comment by na--** [comment]
What would the expected behavior be? :confused:  It's not clear to me how this would work, since when a `FileData` variable is passed as part of an object, the key it is passed with is used in the `multipart/form-data` metadata...

If this was prompted by https://community.k6.io/t/creating-an-arraybuffer-and-sending-it-as-a-file-attachment/1997, them is there a problem with simply sending the raw `ArrayBuffer` contents, if the user doesn't want `multipart/form-data` and instead simply wants to send the file contents as the raw POST body?

**Comment by codebien** [comment]
At this point, this sounds unlikely. As we plan a new HTTP API and maybe FormData+`fetch` support.

Ideally, we should support the following UX:

```js
let formData = new FormData();
formData.append("name", "Bob");
formData.append("profile", imgblob, "profile.png");

let response = await fetch('my-post-endpoint', {
  method: 'POST',
  body: formData,
});
```
