### ISSUE TITLE
Generate k6 script from access.log

### ISSUE THREAD

**Issue by Lamera** [grafana/k6#2107]
## Feature Description

Creating a custom scenario based on real events in the production environment. We have a large web store and it is very difficult to figure out "what" to test in order to simulate the real world in a k6 script. I think with this feature k6 can hold its own better compared to other tools. Especially also that you don't have to deal with creating the test anymore.

## Suggested Solution (optional)
I'm thinking specifically of a converter tool that takes an access.log from apache or nginx and outputs a test.js that can be run directly with k6. The converter should recognize the amount of requests made to the server and calculate the virtual users.

**Comment by na--** [comment]
Thanks for making this issue! 

There might be quite a lot of limitations for such a converter, especially when it comes to non-`GET` requests, since the important details for them generally won't be included in access logs. It will also be difficult to accurately distinguish the traffic of a single user, if you want to record such journeys into separate scenarios... :man_shrugging: That said, having even a poor k6 script as a starting point will probably be better than nothing.

This is a somewhat connected issue: https://github.com/grafana/k6/issues/645

**Comment by mstoykov** [comment]
After internal discussion we decided to close this.

This probably will be better of a separate test generation tool or an extension as @na-- mentioned.
