### ISSUE TITLE
JS - Optional chaining = syntax error

### ISSUE THREAD

**Issue by thim81** [grafana/k6#2168]
When using JS that has the optional chaining syntax, K6 throws a Syntax error:

```
ERRO[0000] SyntaxError: file:///testing/k6/test.js: Unexpected token (6:13)
  4 | 
  5 |     const test = {}
> 6 |     if (test?.test) {
    |              ^
  7 |         console.log('test')
  8 |     }
  9 |  at <eval>:2:28542(106) 
```

## Environment
- k6 version: k6 v0.33.0 ((devel), go1.16.5, darwin/amd64)
- OS and version: MacOS Big Sur

## Expected Behavior

K6 understands the optional chaining "?." syntax and threats the "if (jsonData?.id) {" as "if (jsonData && jsonData.id) {"

## Actual Behavior
K6 throws an error: `ERRO[0000] SyntaxError: file:///testing/k6/test.js: Unexpected token (6:13)`

## Steps to Reproduce the Problem
Enter a script with an IF condition

```
import http from 'k6/http';

export default function () {

    const test = {}
    if (test?.test) {
        console.log('test')
    }

    let res = http.get('https://k6.io');
    console.log(JSON.stringify(res.headers));
}

```

**Comment by thim81** [comment]
@na-- Shall I close the issue, since it is not something that can be resolved in a simple manner?

**Comment by na--** [comment]
@thim81, you can leave the issue open, so that other people who stumble on the same problem can more easily find it. We will close it when we add support for this JS feature in k6. Most likely when [goja](https://github.com/dop251/goja) adds support for it and we update our dependency for it in k6. I don't think the goja author is planning to work on this specific thing any time soon, but he might accept a good PR if someone is interested in contributing it... :man_shrugging: 

Alternatively, they are some other potential means for getting this in k6 in the future. It's _very_ unlikely we'll update the bundled Babel in k6 any time soon, but, for example, in the future we might switch to using [esbuild](https://esbuild.github.io/content-types/#javascript) to automatically transpile newer JS features to something that goja and k6 understand :man_shrugging:  That has its own downsides and problems, so it's not a guarantee, just a potential option down the line.

**Comment by na--** [comment]
FWIW, the latest goja now supports this, but our old version of Babel doesn't :disappointed: More details on our future plans: https://github.com/grafana/k6/issues/2296#issuecomment-993356717
