### ISSUE TITLE
Normalized benchmark for outputs 

### ISSUE THREAD

**Issue by codebien** [grafana/k6#2208]
We should define a set of use cases for getting the ability to test in a reliable way the different available outputs (as an extension or directly supported from the k6 core). We should provide cases defining the number of samples, number of tags, number of concurrent requests accepted, number of cores.

It could be useful both for benchmarking the internal operations of k6 and for integrating with a real server (Prometheus, InfluxDB, TimescaleDB, etc..).

**Comment by yorugac** [comment]
Continuing discussion with @codebien from https://github.com/grafana/xk6-output-influxdb/pull/3#issuecomment-959603290

I've made a quick experiment to check the possibility of relying on metric rate in an Output benchmark. In short, all metrics emitance can be traced down to time periods: per second, per iteration, per HTTP, etc. So long as estimates for how many seconds, iterations, HTTP, etc. in a test run are known, it's possible to calculate how many metrics to expect in an Output.

Experiment code is here:
https://gist.github.com/yorugac/19bf4f395212faea47a7edce317a6958

It outputs something like:
```bash
     c0...................: 249881 499.755528/s
     c1...................: 249881 499.755528/s
     c2...................: 249881 499.755528/s
     c3...................: 249881 499.755528/s
     c4...................: 249881 499.755528/s
     c5...................: 249881 499.755528/s
     c6...................: 249881 499.755528/s
     c7...................: 249881 499.755528/s
     c8...................: 249881 499.755528/s
     c9...................: 249881 499.755528/s
     data_received........: 0 B    0 B/s
     data_sent............: 0 B    0 B/s
     iteration_duration...: 
     iterations...........: 249381 498.755541/s
     vus..................: 499    min=499      max=500
     vus_max..............: 500    min=500      max=500

total: 3498334
received metrics: 16 map[c0:249881 c1:249881 c2:249881 c3:249881 c4:249881 c5:249881 c6:249881 c7:249881 c8:249881 c9:249881 data_received:249881 data_sent:249881 iteration_duration:249381 iterations:249381 vus:500 vus_max:500]
duration: 500
expected sample rate ~ 7000
real sample rate = 6996
```

The formula for sample rate turns out like this:
- `vus` and `vus_max` are emitted once per second
- `data_received`, `data_sent`, `iterations` and `iteration_duration` are emitted once per iteration, though the last two can be absent if iteration is not finished yet (here, iterations are reliably fast so that part gets simplified)
- if HTTP is used, then each HTTP request emits 9 metrics from `http_*` family
- if custom metrics are used, each addition of custom metric gets repeated per iteration

I assume that the exact numbers matter little to an Output here as metric can have value equal to 0 and it still will be a metric sample that must be processed.

The snippet also uses `constant-vus` only, to have a simplified formula. Since the goal is the benchmark and achieving reliable control over metric rate received by an Output, there *should be* little difference what executor is used. I.e. if the Output in question can handle X metrics rate then it can handle it no matter how that rate is achieved.

Obviously, this approach can be improved / extended :)

**Comment by codebien** [comment]
It is still nice to have but at the moment sounds a bit unrealistic, we may re-open in the future. Prometheus remote write already set some good performance, I hope we will improve it with #2557 and set a de-defacto baseline.
