### ISSUE TITLE
[Feature Request]: Add Documentation Template as per new Github Issue forms

### ISSUE THREAD

**Issue by Rutam21** [grafana/k6#2211]
### Feature Description

GitHub has recently rolled out a public beta for their issue forms feature. This would allow us to create interactive issue templates and validate them.

K6 currently doesn't use a documentation template format. The task is to create a GitHub issue form for documentation for this repository.

### Suggested Solution (optional)

A `documentation.yaml` file should be added to be used as the default template for raising any documentation requests for the repository.

 - [ ] Prepare documentation issue form in .github/ISSUE_TEMPLATE/documentation.yaml

**Comment by Rutam21** [comment]
@codebien Please take a look at it and let me know your thoughts on this. Thanks.

**Comment by na--** [comment]
The k6 documentation lives in a separate repository: https://github.com/grafana/k6-docs

So, instead of https://github.com/grafana/k6/pull/2212, we should probably just have a mention of that fact in https://github.com/grafana/k6/issues/new/choose, similar to the way we point users who want to ask questions to the community forum. Which can be done by adding an entry to https://github.com/grafana/k6/blob/master/.github/ISSUE_TEMPLATE/config.yml
