### ISSUE TITLE
TextEncoder is not defined

### ISSUE THREAD

**Issue by dinofei** [grafana/k6#2291]
### Brief summary

It is normal for me to execute script scripts locally, but this error is thrown back when using k6 run

### k6 version

k6 v0.33.0 ((devel))

### OS

go1.16.5, darwin/amd64

### Steps to reproduce the problem

![image](https://user-images.githubusercontent.com/34927614/145701223-bfaa88a0-608b-4aaa-8dc4-2663458013ab.png)

### Expected behaviour

none

### Actual behaviour

none

**Comment by na--** [comment]
This seems like a Web API, not an ECMAScript one: https://developer.mozilla.org/en-US/docs/Web/API/TextEncoder
So it's not available in [goja](https://github.com/dop251/goja), the JS runtime we use to run k6 scripts. Since it's a Web API, I am not sure if goja will even accept a PR for it, but if they don't, we might :man_shrugging: 

Until there is native support for it, it seems like there's a fairly small polyfill: https://github.com/anonyco/FastestSmallestTextEncoderDecoder

It doesn't seem like it works with k6 as it is, but maybe with small modifications it might be a viable alternative?

**Comment by dinofei** [comment]
> This seems like a Web API, not an ECMAScript one: https://developer.mozilla.org/en-US/docs/Web/API/TextEncoder So it's not available in [goja](https://github.com/dop251/goja), the JS runtime we use to run k6 scripts. Since it's a Web API, I am not sure if goja will even accept a PR for it, but if they don't, we might 🤷‍♂️
> 
> Until there is native support for it, it seems like there's a fairly small polyfill: https://github.com/anonyco/FastestSmallestTextEncoderDecoder
> 
> It doesn't seem like it works with k6 as it is, but maybe with small modifications it might be a viable alternative?

Yes, the fastestsmallesttextcoderdecoder library perfectly solves my problem. Thank you very much

**Comment by MStoykov** [comment]
For future reference at least the MDN example works with k6 v0.35.0:
```javascript
import "https://dl.dropboxusercontent.com/s/r55397ld512etib/EncoderDecoderTogether.min.js?dl=0";

export default function() {
        const encoder = new TextEncoder()
        const view = encoder.encode('€')
        console.log(view); // Uint8Array(3) [226, 130, 172]
}
```

**Comment by mstoykov** [comment]
close in favor #2440
