### ISSUE TITLE
More options for custom body files forms

### ISSUE THREAD

**Issue by cethap** [grafana/k6#2298]
### Feature Description

In runtime when I try to write custom head for form body send with javascript, when the file is > to 40 mb the ram is elevated to max and OS kill the porcess.

Example for custom body builder
![image](https://user-images.githubusercontent.com/694041/146058083-95aaa7f8-78ef-40b8-9a3a-aa360a5b7dcd.png)

Normal Use:
![image](https://user-images.githubusercontent.com/694041/146058789-1e3afcab-cdf6-44ed-98ec-87d6d022c019.png)

When execute script with custom body
![2021-12-14_13-33](https://user-images.githubusercontent.com/694041/146058879-e7015df1-6e7b-4389-a5a7-3c6aca5354e5.png)

### Suggested Solution (optional)

I Suggest can have options for build custom head of body forms for correct binding of big files

**Comment by na--** [comment]
Can you please explain in more details what exactly are you trying to do, I don't understand what you mean by "head of body" :confused: Also, do you want to have a unique request body in every VU/iteration/request? Or will it be the same?

Because if it's the same, https://github.com/grafana/k6/issues/1931 (currently WIP) should solve the issue, right? And if it's unique for every request, I am not sure how exactly we can reduce RAM usage with 40+MB uploads... :confused: Maybe some sort of a streaming API (https://github.com/grafana/k6/issues/592) / generator-based on-demand construction of request bodies?

**Comment by cethap** [comment]
Yes It's like a join both, because in this moment I need upload large file to service but the custom body form-data that generate k6 for default is not work for me, then I build a custom body byte array with the correct format for my service (based in Advanced multipart request polyfill), but in this building and when I send http request the memory of my computer rise up in seconds.

When I try to upload without use the polyfill, the memory behavior is normal but the request fails :) for the above explanation

**Comment by na--** [comment]
Do you want to upload the exact same request body in every request?

**Comment by cethap** [comment]
Yes, but in one alone request I can see the excessive memory rise up

**Comment by na--** [comment]
I'm closing this in favor of https://github.com/grafana/k6/issues/2311 and/or https://github.com/grafana/k6/issues/1931. Those issues explore the underlying technical issues and potential solutions for the problem of k6 using too much RAM when users want to upload big files.
