### ISSUE TITLE
Adjust the configuration of the golangci-lint

### ISSUE THREAD

**Issue by olegbespalov** [grafana/k6#2328]
### Feature Description

Inside the k6, we use the `golangci-lint,` a great tool that improves the developer experience and helps produce better code. 

The main point about this (and any tool that projects can use in CI) tool is that it saves a lot of time, helping identify the issues with the code earlier, saving the code review time for the things that matter more. 

The tool itself isn't settled in stone. It's developing, new linters appear, and the old become abandoned. It's a regular cycle of that kind of software.

If we update the tool using the current configuration, we can quickly get the case when a new linter starts screaming about the code that passed all the CI checks yesterday. It can lead to chore PRs like #2324 or #2326. It's not a good developer experience. But on the other side, it's good to have the ability to easy-update the tool since there can be bug fixes for the linters.

The suggestion is to iterate on the configuration and switch from the `enable-all: true` to the list of the linters that matter (make sense). The k6-core team should approve the list of the linters, and the setting of the linters should keep in mind the k6's existing codebase.

For example, in version v1.43.0 of `golangci-lint` is a nice new linter `varnamelen` that can improve the readability of the variables. Still, if it is included without tuning, there can be a lot of false positives ([see the discussion in the PR](https://github.com/grafana/k6/pull/2323)).

It is the standard practice for many of the projects, examples:
* [Loki](https://github.com/grafana/loki/blob/main/.golangci.yml#L58)
* [Tempo](https://github.com/grafana/tempo/blob/main/.golangci.yml#L44)

### Already existing or connected issues / PRs (optional)

https://github.com/grafana/k6/pull/2323

**Comment by na--** [comment]
:+1: yeah, `enable-all` + `disable` is probably a bit too annoying to deal with every update :disappointed: On the other hand, it forces us to evaluate all of the newly introduced linters and if they are useful or not for us... :man_shrugging:  

I am fine if we switch to an enabling individual linters, but here's an alternative proposal that might be ok. What if, in every PR that bumps the golangci-lint version, we also publish a diff between the linter errors that were shown for the whole project (i.e. without `--new-from-rev origin/master`, just pure `golangci-lint run --out-format=tab ./...`) between the old golangci-lint version and the new one? That way we can tweak and disable certain linters that don't make sense for us, while still fairly evaluating any new ones. 

Otherwise, I fear we'll miss a useful linter, for example one that catches errors like these :sweat_smile: 
```go
err := something()
if err != nil {
    return err
}
// ...
if subErr := somethingElse(); subErr != nil {
    return err
}
```
