### ISSUE TITLE
On-demand copy for Response.Request.Body

### ISSUE THREAD

**Issue by codebien** [grafana/k6#2395]
As part of https://github.com/grafana/k6/issues/2311 investigation and as previously reported in https://github.com/grafana/k6/issues/1931#issuecomment-809177427 the `Response.Request.Body` field as a `string` type requires executing a dedicated copy for each request.
This problem creates noise for better profiling of #2311 and it should be required from any solution applied to #2311.

https://github.com/grafana/k6/blob/737dfa7ced6e4f94dbb3d6f2c2837085e783ac09/lib/netext/httpext/request.go#L52-L56

### Suggestion

The current string field is really required only when the JS property is accessed directly. The proposal is to switch to `[]byte` and generate the string only on-demand when the property is accessed from JS. It should allow reusing the original slice used on the HTTP parsing.

The copy should be executed in the Get function for a `goja.Proxy` object. The Proxy wraps the `k6/http.Response` object.

### Example

```js
import http from "k6/http";
import { sleep } from "k6";

const binFile = open("1MB.bin", "b");

export const options = {
        systemTags: [],
	iterations: 1000,
	vus: 200,
};

export default function () {
    const data = {
	field: Math.random(),
	file: http.file(binFile, "testdata.bin"),
    };

    const res = http.post("http://test:8080/upload", data);
    sleep(1);
}
```
![profiling](https://user-images.githubusercontent.com/2103732/155115875-7ef6765d-3607-46da-8d45-b63ed0f87750.png)

**Comment by na--** [comment]
@MStoykov, this is about the copy of the **request** body that is saved in `Response.request.body`, not the response body. So `io.ReadCloser` has nothing to do with it and some sort of an on-demand lazy copy seems like it should be easy to do.

Moreover, this probably is actually a bug, not just very inefficient: https://github.com/grafana/k6/blob/737dfa7ced6e4f94dbb3d6f2c2837085e783ac09/lib/netext/httpext/request.go#L145

For binary bodies, this will likely mangle them... So, I am fine with trying to use a proxy. I am also fine with making a minor breaking change and actually make the property return a lazy-loaded `ArrayBuffer` since it would basically be a bugfix :man_shrugging: Or have it purely on the JS side and reference literally the exact same variable that was passed to `http.request()`, so no copying takes place.

**Comment by codebien** [comment]
> Or have it purely on the JS side and reference literally the exact same variable that was passed to http.request(), so no copying takes place.

@na-- Do you mean totally dropping the `response.request` object? If not, can you provide an example of the expected API? For example, how should be the following use case?

```js
export default function () {
  const url = 'http://test.k6.io/login'

  const payload = JSON.stringify({
    email: 'aaa',
    password: 'bbb',
  })

  const params = {
    headers: {
      'Content-Type': 'application/json',
    },
  }
  let res = http.post(url, payload, params)
  console.log(res.request.headers)
}
```

**Comment by na--** [comment]
> > Or have it purely on the JS side and reference literally the exact same variable that was passed to http.request(), so no copying takes place.
> 
> @na-- Do you mean totally dropping the `response.request` object? 

No, I mean the **exact same `goja.Value`** that is potentially given as `args[0]` here: https://github.com/grafana/k6/blob/737dfa7ced6e4f94dbb3d6f2c2837085e783ac09/js/modules/k6/http/request.go#L57-L67

Can be threaded through the code and returned by the `Proxy` (or whatever) as `Response.request.body`. This will mean literally no copying on the Go side for this specific usage of the request body.

> If not, can you provide an example of the expected API, please? For example, how should be the following use case?
> ...

Exactly what is currently returned - if technically possible, I propose no changes to anything in `Response.request` besides `body`.

**Comment by MStoykov** [comment]
> @MStoykov, this is about the copy of the request body that is saved in Response.request.body, not the response body. So io.ReadCloser has nothing to do with it and some sort of an on-demand lazy copy seems like it should be easy to do.

My mistake :facepalm: 

This still doesn't really work for *all* cases. 

`http.post(url, {something : here, file: http.file(...)}...)`  should the `response.request.body` in this case be the given object?
What is the point of having the `response.request.body`.

And an example that I kind of give in #2311 (but not as heads on as I remember):
```javascript
const data = new ArrayBuffer(8);
const view = new Int32Array(buffer);
view[0] = 20;
let response1 = http.post(url, data)
// some more code
view[2] =23;
let response2 = http.post(url, data)
// some more code
// What is the value of `response1.request.body` here? 
```

Also while we still don't have asynchronous code - we soon should be able to have one in which case this is even a potential race condition
```javascript
...
http.asyncPromise(url, data).then(....)
view[3]=12
http.asyncPromise(url2, data).then(....)
...
```

Again this feels like we are trying to patch the problem while IMO the problem is systemic in the API and the fix should be to *move* to a different API that doesn't have those problems. This also will be a really good promotion of the new API - "it works way better than the previous one"

**Comment by na--** [comment]
> should the `response.request.body` in this case be the given object?

Ideally no, but what I said in https://github.com/grafana/k6/issues/2395#issuecomment-1048004912 is that I would be fine with that compromise if we couldn't implement something better, e.g. a no-copy `Proxy` or a direct `ArrayBuffer` reference to the `[]byte` sent or something along these lines...

> What is the point of having the `response.request.body`.

There is probably very little point in `Response.request.body` in general and should have probably never been included. But now that it's there, it may allow someone to more easily correlate responses? :man_shrugging: 

> Again this feels like we are trying to patch the problem while IMO the problem is systemic in the API and the fix should be to move to a different API that doesn't have those problems. This also will be a really good promotion of the new API - "it works way better than the previous one"

Maybe, but fixing this unnecessary and wrong string copying won't make all of these efforts worse (esp. if the `Proxy` can be made read-only), while it will immediately and substantially reduce memory usage of existing scripts. So I suggest we do both and we start with this fix.

**Comment by codebien** [comment]
Closing as we prefer to directly address the core problem in the new HTTP API.
