### ISSUE TITLE
Move integration tests to a dedicated package

### ISSUE THREAD

**Issue by na--** [grafana/k6#2459]
https://github.com/grafana/k6/pull/2412 and its preceding PRs refactored some cruft in `cmd/` and allowed us to safely and easily write full integration tests of k6. However, these tests are limited to `cmd/`, since the `globalTestState` and `globalState` types, as well as the helper functions and other types they depend on are not exported: https://github.com/grafana/k6/blob/6d7d732d8798b30904f5a75d779f93aaf7770450/cmd/root_test.go#L18-L30

As evidenced by https://github.com/grafana/k6/pull/2399#issuecomment-1077753466, it would be much better to further refactor `cmd/`, to export and maybe even move these types out of there into a new package or packages, so we can have a dedicated top-level `tests/` or `integration_tests/` package where we could organize these tests nicely.

**Comment by olegbespalov** [comment]
Are we going to tackle this in the [v0.39.0](https://github.com/grafana/k6/milestone/23)? :thinking: 

I'm asking because if yes, I'd like to merge the https://github.com/grafana/k6/milestone/23 as it is (in [v0.38.0](https://github.com/grafana/k6/milestone/22)), and move the tests to a separate module in the next cycle.

**Comment by na--** [comment]
Yeah, I think we should leave it for the next release, possibly start this cooldown. I think it's relatively urgent that we do it because a whole bunch of not-quite-ok integration tests will start piling up until we do, and so I added the `high prio` tag... But it's not so urgent that we need to drop things to get it done in this release, we already have plenty of integration test goodness for this one, even if it's not quite as user-friendly as I'd like :sweat_smile:

**Comment by imiric** [comment]
@na-- I started looking into this, and have a couple of questions:

- Since the goal is to export `globalTestState` and related types, and move them to a separate package, this means we'd also need to export [`cmd.globalState`](https://github.com/grafana/k6/blob/24f9871266fd59d4079929c7c6d95454461049b5/cmd/root.go#L60) (since `testGlobalState` embeds it).

  But [this comment](https://github.com/grafana/k6/blob/24f9871266fd59d4079929c7c6d95454461049b5/cmd/root.go#L52-L55) mentions that we want to _prevent_ direct access to some of these fields from the rest of the codebase. So how do you envision this working?

- What other non-`cmd` integration tests do you have in mind that we should add?

  Currently these test types are only useful for `cmd` integration tests, which look fine to me being in `cmd/`.

  If we have tests in mind for other packages, it would help determine what exactly needs to be exported, and what can remain in `cmd/`.

**Comment by na--** [comment]
> Since the goal is to export `globalTestState` and related types, and move them to a separate package, this means we'd also need to export [`cmd.globalState`](https://github.com/grafana/k6/blob/24f9871266fd59d4079929c7c6d95454461049b5/cmd/root.go#L60) (since `testGlobalState` embeds it).

Not quite - we'd will definitely need to export `cmd.GlobalState`, and I don't see a need to move it to a separate package. `cmd` is probably fine. We can probably get away with not exporting `globalTestState`, it should be able to remain private for just the package with the integration tests :thinking:  Though, as my comment below explains, even exporting both and having them in a separate package is probably not a big deal.

>  But [this comment](https://github.com/grafana/k6/blob/24f9871266fd59d4079929c7c6d95454461049b5/cmd/root.go#L52-L55) mentions that we want to _prevent_ direct access to some of these fields from the rest of the codebase. So how do you envision this working?

Even if we export `cmd.GlobalState`, nothing else in the codebase is actually going to be able to use it because of import loops. The `cmd/` package is essentially the k6 entry point, the root of the import tree that eventually reaches all other modules in k6. Only modules "above" it, like the one with integration tests, will be able to import and use it. So no regular k6 module should be able to import the cmd or the integration tests package without an import loop.

That said, if we need to, I don't even see a problem with having the `GlobalState` and `GlobalTestState` in separate packages, outside of `cmd/`, so they could technically be import-able by other modules :thinking: It might even make things cleaner. We can juse keep the [`newGlobalState()`](https://github.com/grafana/k6/blob/24f9871266fd59d4079929c7c6d95454461049b5/cmd/root.go#L82-L137) and [`newGlobalTestState()`](https://github.com/grafana/k6/blob/24f9871266fd59d4079929c7c6d95454461049b5/cmd/root_test.go#L30-L87) constructors private, so other packages are not tempted to use them, and be careful in how we propagate the actual objects down to the rest of the code :thinking: 

It is a balance between cleanliness and usability, but our goal is not to completely prevent such things. We need to make it easy to use these mock-able objects and to make it obvious that it's a bad idea to mess with the OS and the external environment directly, that all interactions have to pass through these objects. However, nothing is stopping any k6 module (or an xk6 extension) to directly import the `os` package and do whatever it wants. We can't prevent that, we just have to make the better approach easy and obvious.

> What other non-`cmd` integration tests do you have in mind that we should add?

Nothing, only integration tests. That is, these tests that essentially start from the root of k6 and run an almost version of the code. I think the only part of k6 that is not touched by the integration tests is [`newGlobalState()`](https://github.com/grafana/k6/blob/24f9871266fd59d4079929c7c6d95454461049b5/cmd/root.go#L82-L137)...

However, some currently existing "integration tests" that are outside of the main `cmd/` module, [like these ones](https://github.com/grafana/k6/tree/master/cmd/integration_tests), unfortunately don't fall under this category... :disappointed: They are what made me create this issue. Since they can't import `globalTesState`, they have to re-implement [a bunch of boilerlpate code from `cmd/run.go` and elsewhere](https://github.com/grafana/k6/blob/24f9871266fd59d4079929c7c6d95454461049b5/cmd/integration_tests/eventloop/eventloop_test.go#L31-L83), just so they can run the test. This makes them harder to maintain (we have to update these tests often when we change something internal) and less reliable (they might not re-implement the test run logic exactly as a normal k6 run will). 

And, crucially, they don't need any of these internal implementation details to actually verify whatever they are testing. They are just forced to re-implement them because they don't have access to the `globalTesState` if they need to be in a separate package. And they need to be in a separate package because they [pollute with the modules registry](https://github.com/grafana/k6/blob/24f9871266fd59d4079929c7c6d95454461049b5/cmd/integration_tests/eventloop/eventloop_test.go#L87-L89), which unfortunately (because of how xk6 works) needs to be a global variable. Having the integration test in a separate package ensures that this pollution is limited only to the test, because of how Go executes tests.

> Currently these test types are only useful for `cmd` integration tests, which look fine to me being in `cmd/`.

See :arrow_up:, some integration tests actually need to be in a separate package. But we might want to move even the ones that are fine in `cmd/` eventually, simply because may be easier to organize and nicer to review and add new tests if they can have their own package(s).

**Comment by imiric** [comment]
>> What other non-`cmd` integration tests do you have in mind that we should add?

> Nothing, only integration tests. That is, these tests that essentially start from the root of k6 and run an almost version of the code. I think the only part of k6 that is not touched by the integration tests is newGlobalState()...

No, I meant, what other integration tests that are _not_ related to `cmd` you had in mind. If the entry point will always be `cmd`, I reiterate my point that these integration tests should continue to exist in `cmd`.


> However, some currently existing "integration tests" that are outside of the main `cmd/` module, [like these ones](https://github.com/grafana/k6/tree/master/cmd/integration_tests), unfortunately don't fall under this category... :disappointed: They are what made me create this issue.

Ah I see, but these tests are lower level than `cmd` integration tests. The definition of an "integration test" is broad and fuzzy, but I see these as more lower level and white-boxy (setting up the init state, JS runner, and running the `ExecutionScheduler` directly), whereas the `cmd` tests that use `globalState` work on a higher level and are more black-boxy (they set args, flags, standard streams, etc., and run k6 commands).

So I don't see [this](https://github.com/grafana/k6/blob/24f9871266fd59d4079929c7c6d95454461049b5/cmd/integration_tests/eventloop/eventloop_test.go#L31-L83) as boilerplate. It's more of the required test setup for the level they're written in. If we had a need for more tests at this level, then it would make sense to abstract this away. If not, as you seem to imply, and it only adds maintenance headaches, then sure, let's convert them to `cmd` integration tests instead.


> See :arrow_up:, some integration tests actually need to be in a separate package. But we might want to move even the ones that are fine in `cmd/` eventually, simply because may be easier to organize and nicer to review and add new tests if they can have their own package(s).

Got it. Makes sense.

The reason I'm reluctant to move `globalState` (and thus `globalTestState`) outside of `cmd` is because it's _very_ specific to `cmd`. It contains fields like `stdOut`/`stdErr`/`stdIn`, `args`, `flags`, `fs`, etc. But I guess it would be fine to export it while keeping it in `cmd`, and just rely on the fact that import loops will prevent any other non-test package from accessing it. `globalTestState` can remain unexported in a different package, as you say.

I'll experiment a bit with this, but my rough plan so far is to:

1. Export `cmd.globalState`, and keep it in `cmd`.

2. Move `globalTestState` and all integration tests currently in `cmd` to `cmd/integration_tests` or just `cmd/tests`. Since there are no non-`cmd` integration tests at this level, it makes more sense to keep these as a subtest of `cmd`, rather than e.g. a new root package.

3. Rewrite the current `cmd/integration_tests` into `cmd` integration tests (this reads funny :sweat_smile:, but you get what I mean: to use `globalTestState`).

Does this sound good?

**Comment by na--** [comment]
> Ah I see, but these tests are lower level than `cmd` integration tests. The definition of an "integration test" is broad and fuzzy, but I see these as more lower level and white-boxy (setting up the init state, JS runner, and running the `ExecutionScheduler` directly), whereas the `cmd` tests that use `globalState` work on a higher level and are more black-boxy (they set args, flags, standard streams, etc., and run k6 commands).

What I was trying to say is that these tests are currently lower level, but they didn't need to be lower level. They were forced to be white-boxy because they didn't have access to the `globalState` and `globalTestState`. There is no technical reason why they couldn't be simplified to rely on it, like the other integration tests. They will simultaneously become simpler, more robust and easier to maintain, and better tests (closer to reality).

> The reason I'm reluctant to move `globalState` (and thus `globalTestState`) outside of `cmd` is because it's _very_ specific to `cmd`. It contains fields like `stdOut`/`stdErr`/`stdIn`, `args`, `flags`, `fs`, etc. But I guess it would be fine to export it while keeping it in `cmd`, and just rely on the fact that import loops will prevent any other non-test package from accessing it. `globalTestState` can remain unexported in a different package, as you say.

I somewhat disagree, it's not very specific to `cmd/`. Again, the purpose of `globalState` is not to be inaccessible from the rest of the code. The goal is for everything inside k6 to use it (or its properties), and not the `os` package directly, so everything can actually be reliably tested with these integration tests that use the `globalTestState` mocks, without any side-effects like polluting the actual process environment. 

It just so happens that the majority of `globalState`'s direct usage is in `cmd/`, for now. However, most of its properties like the [file system](https://github.com/grafana/k6/blob/24f9871266fd59d4079929c7c6d95454461049b5/cmd/test_load.go#L157-L164) and [`stdOut`/`stdErr`/etc.](https://github.com/grafana/k6/blob/24f9871266fd59d4079929c7c6d95454461049b5/cmd/run.go#L217-L226) are threaded and propagated throughout the rest of k6. So it's not going go be a big deal to pass the whole `globalState` somewhere outside of `cmd/`, it may even simplify some things in the future, who knows...

The only reason not to do something like this would be to _gently_ encourage lower-level components inside of k6 to avoid directly querying the "raw" environment and use other finer-grained abstractions instead. For example, instead of reading an env variable, to query the value from the `Options`. However, as long as that querying happens from `globalState.envVars` and not `os.Environ`, everything is still perfectly fine, we would still be able to test the behavior in an idempotent integration test. 

If we want to go to extremes, I'd definitely prefer to have the whole `GlobalState` object available everywhere in the k6 code, even if we don't need all of it, than to need some of its properties somewhere deep in the code and have to either use `os` directly, or refactor half the codebase to thread that single property to that specific place. 

> I'll experiment a bit with this, but my rough plan so far is to:
> 1. Export `cmd.globalState`, and keep it in `cmd`.
>
> 2. Move `globalTestState` and all integration tests currently in `cmd` to `cmd/integration_tests` or just `cmd/tests`. Since there are no non-`cmd` integration tests at this level, it makes more sense to keep these in a subpackage of `cmd`, rather than in e.g. a new root package.

Hmm I kind of think it will be simpler to just have `GlobalState` exported in a sub-package of `cmd/`, e.g. `cmd/state`. And have its constructor [`newGlobalState()`](https://github.com/grafana/k6/blob/24f9871266fd59d4079929c7c6d95454461049b5/cmd/root.go#L82-L137) unchanged - unexported and in `cmd/`. We don't need to use it outside of `cmd/` yet, but if we ever need to, we won't have to rewrite the whole `cmd/` code once again.

Similarly, `GlobalTestState` can be exported and moved to a cmd sub-package, e.g. `cmd/tests/global_test_state.go` or `cmd/integration_tests/global_test_state.go`. Most of the integration tests can be in the same package, but other ones (e.g. ones that add JS or output modules and pollute) can be in sub-packages. It's important that `GlobalTestState` is not actually in a `_test.go` file, since then standalone integration tests (in their own package) won't be able to import it, I think.

**Comment by imiric** [comment]
Hey, I'm done with most of the changes we agreed on, but have a question about which tests should be moved to `cmd/tests`. Which ones are "integration" tests, essentially.

I moved all of the ones in [`cmd/integration_test.go`](https://github.com/grafana/k6/blob/a2ab89abfdc8c12fa28b3d25092b2a1d9310f8c4/cmd/integration_test.go), but should most of [`cmd/archive_test.go`](https://github.com/grafana/k6/blob/a2ab89abfdc8c12fa28b3d25092b2a1d9310f8c4/cmd/archive_test.go) and [`cmd/run_test.go`](https://github.com/grafana/k6/blob/a2ab89abfdc8c12fa28b3d25092b2a1d9310f8c4/cmd/run_test.go) also be moved?

I'm inclined to say "yes", and to consider an integration test any test that runs `newRootCommand().execute()`. Everything else should be a unit test that stays in `cmd`. Sounds good?
