### ISSUE TITLE
add additional metrics

### ISSUE THREAD

**Issue by kostiamol** [grafana/k6#2478]
### Feature Description

I need to calculate latency duration of grpc request in grafana from data in prometheus using the formula:
`sum(rate(k6_grpc_req_duration_bucket{name="${K6RequestName}"}[$__rate_interval])) by (le)
`
but such bucket is missing

a similar situation is with mean latency - `sum` and `count` are missing:
`1000*sum (rate(k6_grpc_req_duration_sum{name="${K6RequestName}"}[$__rate_interval]))/sum (rate(k6_grpc_req_duration_count{name="${K6RequestName}"}[$__rate_interval]))`

**Comment by codebien** [comment]
Hi @kostiamol,
I'm closing this because I already replied to your forum's post. https://community.k6.io/t/prometheus-grafana-count-sum-bucket/3375/3

In any case, if you want to open an issue for submitting a feature request providing your use case the Prometheus output extension is the right repository. https://github.com/grafana/xk6-output-prometheus-remote/issues
