### ISSUE TITLE
cmd/env for executor type OR the entire options object 

### ISSUE THREAD

**Issue by kkriegkxs** [grafana/k6#2556]
### Feature Description

Add ability to specify the executor type via cmd or env var and a set of corresponding configs (which the i/u counts and stages are already implemented).
OR optionally (no pun intended) provide the entire options object either as an external file path or json string.

The intent is to enable specifying different options for multiple scripts executing in parallel (for the ease of automation)

**Comment by mstoykov** [comment]
Hi @kkriegkxs, 

>  OR optionally (no pun intended) provide the entire options object either as an external file path or json string. 

This is possible even now. 
```
SOME_VAR="{all the json you want}" k6 run script,js
```
script.js:
```javascript
export let option = JSON.stringify(__ENV.SOME_VAR);
... 
```

As for the rest, given the above "workaround" and the fact that configuration in k6 already is really complex to work with and write and this will make it even more so - I very much doubt the k6 team will:
1.  introduce such a change before #883
2. Even after the above issue is fixed - prioritize this, given the workaround that does 90% of what a real fix will do. 

Will keep this open to let others give their opinion and so that there is an open issue about it ;)
