### ISSUE TITLE
Preventing storing environment variables' values in archive

### ISSUE THREAD

**Issue by olegbespalov** [grafana/k6#2587]
# What?

Add a new flag to a `k6 archive` that will prevent storing environment variables (passed with the `--env`) in the archive's `metadata.json`.

# Why?

Sometimes scripts can use the environment variables in the init context and it's not possible to produce an archive without passing them, however storing the actual values of the environment variables can be harmful from the security perspective.

**Comment by mstoykov** [comment]
To me it seems like dropping *all* env variables will be worse experience. A lot of people do use env variables to configure/scale their scripts apart from providing it with secrets/credentials.

IMO it will be easier if we provide a way to specify which env variables to be removed. Listing every one separately might be way too much work so maybe having a way to specify a `glob` pattern(s) that if matched will remove an env variable? 

Something like `k6 archive --remove-env SECRET* --remove-env ANOTHER_ONE script.js`?

 WDYT?

**Comment by olegbespalov** [comment]
> To me it seems like dropping all env variables will be worse experience. A lot of people do use env variables to configure/scale their scripts apart from providing it with secrets/credentials.

@mstoykov I guess if the people use the variables, they can simply not use the new flag (and pass the secrets whenever they run the archive). 

On the other side, the case that covers this PR just excludes from storing everything that passed (only `--env` variables) to the `k6 archive`.

**Comment by mstoykov** [comment]
> I guess if the people use the variables, they can simply not use the new flag (and pass the secrets whenever they run the archive). 

They could, but arguably the idea is to make it useful for more people. 

And I would argue being able to do `k6 cloud --remove-env SECRET* -r VU_COUNT=1000 script.js` is fairly important. And because in practice if you want to not save the credentials ... you don't have a choice really. You either will use this new flag and have it, but will have to set everything through the cloud UI . Which I would argue will not work for this case. Or you just put all the env variables in.
