### ISSUE TITLE
Templating issue in latest k6 release

### ISSUE THREAD

**Issue by varghesevv** [grafana/k6#2623]
### Brief summary

javascript templating with backtick symbol is not working on latest k6 releases. It is working up to release "grafana/k6:0.39.0-24-g0127a508", not anything after that

referenced the example from this url - https://k6.io/docs/test-types/load-testing

### k6 version

0.39.0-25-ge2316a28

### OS

linux ubuntu

### Docker version and image (if applicable)

grafana/k6:0.39.0-25-ge2316a28

### Steps to reproduce the problem

working fine with this command
```docker run -v ${PWD}:/test grafana/k6:0.39.0-24-g0127a508 run /test/test-1.js```

not working with this
```docker run -v ${PWD}:/test grafana/k6:latest run /test/test-1.js``` or
```docker run -v ${PWD}:/test grafana/k6:0.39.0-25-ge2316a28 run /test/test-1.js```
```
/* conf-test-1.js */
export const options = {
  stages: [
    { duration: '5s', target: 2 } 
  ],
  thresholds: {
    'http_req_duration': ['p(99)<1500']
  },
};

export function get_url(){
  return `${BASE_URL}/auth/token/login/`;
}


/* test-1.js */

import http from 'k6/http';
import { check, group, sleep } from 'k6';

import { get_url } from './conf-test-1.js'
export { options } from './conf-test-1.js'

const BASE_URL = 'https://test-api.k6.io';
const USERNAME = 'TestUser';
const PASSWORD = 'SuperCroc2020';

export default () => {
  const loginRes = http.post(get_url(), {
    username: USERNAME,
    password: PASSWORD,
  });

  const authHeaders = {
    headers: {
      Authorization: `Bearer ${loginRes.json('access')}`,
    },
  };

  const myObjects = http.get(`${BASE_URL}/my/crocodiles/`, authHeaders).json();
  check(myObjects, { 'retrieved crocodiles': (obj) => obj.length > 0 });

  sleep(1);
};


### Expected behaviour

Should work with javascript templates

### Actual behaviour

```time="2022-07-29T09:55:54Z" level=error msg="ReferenceError: BASE_URL is not defined\n\tat get_url (file:///test/conf-test-1.js:13:12(1))\n\tat file:///test/test-1.js:12:29(8)\n\tat native\n" executor=ramping-vus scenario=default source=stacktrace```

**Comment by mstoykov** [comment]
There is nothing wrong with the templating if you look carefully the problem is that `BASE_URL` isn't defined in `conf_test-1.js` which it *isn't*.

Previous to https://github.com/grafana/k6/pull/2571 though all variables in the main module/script were globally available which was definitely a *bug*.

With the future addition of native [ESM support](https://github.com/grafana/k6/pull/2563) this would break either way as ... well native modules don't expose their variables globally.

If you want to have access to a variable globally you should be using [`globalThis`](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/globalThis). So in this particular case changing to `globalThis.BASE_URL = ....` should fix it everywhere. 

Sorry for the breaking change, but this definitely was never documented or expected to work like that. If anything given that we say that we support ESM (not natively) it is expected to not work like that at all ;).
