### ISSUE TITLE
Error when run with more than 20.000 vus

### ISSUE THREAD

**Issue by hnhai** [grafana/k6#2649]
### Brief summary

I have a script just call to GET REST API
With 20.000 vus it working normaly, but after 20.000 error: wsarecv: An existing connection was forcibly closed by the remote host appear.
Machine running K6 Windows 10, 32 core, 64gb memory. How can I fix it ? Thanks

### k6 version

v0.39.0

### OS

Windows 10 (32 core, 64gb memory)

### Steps to reproduce the problem

Script file call to simple REST API with more than 20.000 vus (30.000 vus, 50.000 vus)

### Expected behaviour

It works normaly

### Actual behaviour

Error: wsarecv: An existing connection was forcibly closed by the remote host appear

**Comment by hnhai** [comment]
@na-- I see our server serource used still under 50%.

**Comment by hnhai** [comment]
But I think bottle neck can be Api gateway. Let me check it

**Comment by na--** [comment]
> @na-- I see our server serource used still under 50%.

Fair enough, but that doesn't actually guarantee anything. It could be running out of file handles or ports or RAM or just have weird logic for handling incoming requests. Or, as you say, an API gateway or a proxy might be failing.

The error you see in k6 clearly states that the "connection was forcibly closed by the remote host". While this might be a bug in k6 (or, rather, in Windows or the Go standard library), it's much more likely that the problem is actually on the server/gateway, as it says in the error message. The `wsarecv` part of this error message probably comes from this [Win32 API function](https://docs.microsoft.com/en-us/windows/win32/api/winsock2/nf-winsock2-wsarecv), which probably the Go runtime uses to manage the connection. 

So yeah, I am pretty sure this is not a k6 bug. Instead, it seems like k6 might have helped you find a limitation in your setup, which is kind of its main purpose :sweat_smile: :tada: 

In the future, please open such topics in the community forum first, if you're not sure they are k6 bugs: https://community.k6.io/
