### ISSUE TITLE
Support wildcards in options.hosts

### ISSUE THREAD

**Issue by tom-miseur** [grafana/k6#2724]
### Feature Description

It would be useful if it were possible to use wildcards in `options.hosts` in the same way we can with [blockHostnames](https://k6.io/docs/using-k6/k6-options/reference/#block-hostnames).

So instead of:

```javascript
export const options = {
  hosts: {
    'subdomain1.k6.io': '1.2.3.4',
    'subdomain2.k6.io': '1.2.3.4',
  },
}
```

One could specify any subdomain:

```javascript
export const options = {
  hosts: {
    '*.k6.io': '1.2.3.4',
  },
}
```

**Comment by eugercek** [comment]
May I pick this up?

**Comment by na--** [comment]
@eugercek, sure, though please make sure to add plenty of tests and ideally also some benchmarks.

**Comment by eugercek** [comment]
I have some questions to proceed:
1. I found the Trie implementation from #1532 and used the same approach to handle wildcards. But there's one difference `options.hosts` need to store a (`IP` or `P:Port`), so I created a new type. Since we use, don't use 1.18 can't use generics to create a generic type. Is it ok to introduce a new type? The new type: https://github.com/eugercek/k6/blob/wildcard-host/lib/types/addresstrie.go#L35 
  - There are two types:
    - `matchTrieNode` is a trie node with leaf indication as a value( not empty string).
    - `AddressTrie` wrapper around `matchTrieNode`.

2. Currently, `hosts` doesn't do hostname validation should I add it?

3. What are your opinions on moving to iterative trie implementation rather than the current recursive approach?

4. Because of circular dependency, I can't import `go.k6.io/k6/lib` from the `types` package. Ideally, using `types.NewAddressTrie()` with a `lib.Hostaddress` argument would be better, but not sure how to proceed.
  - Currently, I get it as a string and will handle it in `Dialer`
  - Maybe can use `net.TCPAddr`

**Comment by na--** [comment]
Closed by https://github.com/grafana/k6/pull/2747

**Comment by tom-miseur** [comment]
Thank you very much for your contribution, @eugercek!
