### ISSUE TITLE
Publish k6 as a package in alpine

### ISSUE THREAD

**Issue by ASaiAnudeep** [grafana/k6#2731]
### Feature Description

It would be great, if **k6** is available as a package in [alpine](https://pkgs.alpinelinux.org/packages).

```dockerfile
FROM alpine
RUN apk add k6
```

### Suggested Solution (optional)

I have found alternative solution [here](https://community.k6.io/t/trying-to-install-k6-in-alpine-linux-container-failing-miserably/256/2).

```dockerfile
FROM loadimpact/k6:latest AS k6official
// ... 

FROM ... // your image
// ...
COPY --from=k6official /usr/bin/k6 /usr/bin/k6
```

**Comment by na--** [comment]
I have no idea on how one adds a package to Alpine Linux, but in general, package maintainers from the linux distro pick the packages that they will support. We can't do anything about it on our side, except maybe offer support if they reach out.

The most we can do is to add a custom repository with a self-built package in the Alpine Linux .apk style, the same as we currently do for .deb and .rpm packages :thinking: This is currently not a priority for the team, since we already offer an alpine-based docker image, but we might merge a PR with it, if someone else contributes a high-quality one :thinking: 

Some potentially useful links for that effort:
- https://wiki.alpinelinux.org/wiki/Alpine_Package_Keeper
- https://wiki.alpinelinux.org/wiki/Creating_an_Alpine_package

**Comment by olegbespalov** [comment]
After an internal discussion, the k6 maintainer's team decided to close this issue since, unfortunately, maintaining the Alpine (like any other Linux package distribution) package is out of our capacity
