### ISSUE TITLE
Support for encrypted PKCS8 or PKCS12 private keys

### ISSUE THREAD

**Issue by ennoucas** [grafana/k6#2834]
### Feature Description

Hello, encrypted pkcs8 and pkcs12 keys are the only format available in my company. When do you think this will become available with k6? Or do you have any other way / library / extension to make it work with k6 already?

Thanks,
Lucas

**Comment by na--** [comment]
Please explain your use case in detail. What exactly do you mean by "Support for encrypted PKCS8 or PKCS12 private keys"? Support where? What do you want to do with these keys?

If it's about making requests with such client keys, I think the [`tlsAuth` option](https://k6.io/docs/using-k6/k6-options/reference/#tls-auth) already supports them, though I am not 100% sure. Unfortunately, it is only globally configurable (https://github.com/grafana/k6/issues/2186), so it's not very flexible :disappointed: 

Or do you want to encrypt/decrypt arbitrary data with such keys during the k6 script execution? If so, we are already working on implementing the [WebCrypto APIs](https://developer.mozilla.org/en-US/docs/Web/API/Web_Crypto_API) in k6 in https://github.com/grafana/xk6-webcrypto. That extension will likely be merged as a built-in `k6/experimental` module in the not-too-distant future, so it might suit your needs :crossed_fingers: 

Or do you want to do something else with such keys? :sweat_smile: Please elaborate with your specific use case and needs.

**Comment by ennoucas** [comment]
Hi, 
If you try to use encrypted PKCS8 cert with `tlsAuth` option you'll get an error saying k6 does not support encrypted private keys. 
If you try to use PKCS12 with `tlsAuth` it does not work either. 

I want to be able to do api calls with the certs provided by my company that only provide these formats. There's not a lot of documentation on what type of certification is permitted with `tlsAuth` option.

**Comment by na--** [comment]
Ah, I see, this is the relevant part of the k6 code: https://github.com/grafana/k6/blob/d81bb4162517064bdaf9b23bc15062e08184757d/lib/options.go#L166-L169

It was added in https://github.com/grafana/k6/pull/2488 and the limitation seems quite intentional. I _think_ it is because the Go standard library doesn't have support for it, and probably doesn't plan to add support for it any time soon, see https://github.com/golang/go/issues/8860 :thinking: 

Not sure we'd want to import some custom library just to deal with this corner case... Maybe it will be better to solve https://github.com/grafana/k6/issues/2186 and rely on [WebCrypto's ability to decode PKCS8 keys ](https://developer.mozilla.org/en-US/docs/Web/API/SubtleCrypto/importKey#parameters) :thinking: 

In any case, until this issue is solved in either way, it seems like k6 only supports private keys that are encrypted like this, though I am unsure how you can convert your keys to that format, sorry: https://github.com/grafana/k6/blob/d81bb4162517064bdaf9b23bc15062e08184757d/lib/options_test.go#L336-L345
