### ISSUE TITLE
Headers getting appended to the next request

### ISSUE THREAD

**Issue by AravindAlsha** [grafana/k6#2857]
### Brief summary

Consider that there are two APIs with each having a few headers in a collection.

Problem:
When we convert the postman script into k6 script and if we try executing the script then 
1. First API gets successfully executed 
2. In the second API the headers of the first API also gets appended with it current header which leads to the API failure.

I did a simple change in the core.js which helped me to over come the issue temporarily.
We dont pass the headers under options as the header values keep on changing for each of the request
if (setting.options && setting.options.headers) {
   // requestHeaders = Object.assign(setting.options.headers, headers);
   requestHeaders =  headers;
  }

### k6 version

k6 v0.42.0

### OS

Windows 10

### Steps to reproduce the problem

1.Have multiple APIs with headers as part of single collection
2.Run the k6 script to see the headers getting appended for the next consequent request

### Expected behaviour

Headers should not get appended. The headers that are listed under that API only should get passed with the request

### Actual behaviour

Headers is getting appended for each request

**Comment by imiric** [comment]
Hi there,

this seems to be an issue with the [postman-to-k6 converter](https://github.com/grafana/postman-to-k6/).

I haven't verified it, but I think you're right that the headers would be merged for all requests part of the same Postman collection.

However, I'm not sure if this is a desired behavior or not. Does it work the same way in Postman? If you define headers for a collection, do all requests inherit those headers? I would assume there would be a way to override them per request, but I'm not a Postman user.

Or is the issue that you're seeing requests from different collections inherit the same headers?

In any case, the grafana/postman-to-k6 project has been deprecated, but there appears to be an active fork at [apideck-libraries/postman-to-k6](https://github.com/apideck-libraries/postman-to-k6). Can you try if that one has the same issue?

Though I'll close this, since it's not a k6 issue. If you continue to have problems, please open it in the relevant project's issue tracker.
