### ISSUE TITLE
nested collection variables not replaced

### ISSUE THREAD

**Issue by elba02md** [grafana/k6#2872]
### Brief summary

K6 not replace nested collection variables in queries URL during load tests

### k6 version

v0.42.0

### OS

windows 10 entreprise

### Steps to reproduce the problem

hello,
I'm using K6 to run load tests but, I have an issue with nested variables for the collection:
my script code look like this snippet
postman[Symbol.for("initial")]({
  options,
  collection: {
    baseUrl: "http://localhost:8080",
    "api-common-path": "api/v1",
    "api1-path": "{{baseUrl}}/{{api-common-path}}/cours",
    "api2-path": "{{baseUrl}}/{{api-common-path}}/articles",
    "api3-path": "{{baseUrl}}/admin/cache"
  }
});

when I run apis with postman, everything is ok, but when I use k6 run script.js, the nested variables are not replaced and therefore, it can't reach the server.
this msg appear for each api called:  error="Get \"http:///%7B%7BbaseUrl%7D%7Dapi7Bcommon7Bpath/cours\": http: no Host in request URL"

Is this missing due to a bug or not supported?

for now, I'm using postman pre-script as a workaround

Thanks in advance

### Expected behaviour

replace nested variables in query url

### Actual behaviour

nested variables not replaced in query url

**Comment by na--** [comment]
Hey, sorry for the slow response! This seems to be an issue with a script produced by the [postman-to-k6 converter](https://github.com/grafana/postman-to-k6/), right? I haven't verified it and I am very far from a Postman expert, but it seems like it might indeed be a bug.

Unfortunately, the `grafana/postman-to-k6` project was deprecated a while ago and is not actively maintained. There is an  active fork at [apideck-libraries/postman-to-k6](https://github.com/apideck-libraries/postman-to-k6). Can you try if that one has the same problem? 

I'll close this, since it's not a k6 issue. If you still experience the problem with scripts produced by `apideck-libraries/postman-to-k6`, you should probably open an issue in their repo.
