### ISSUE TITLE
Compatibility with z/OS Unix

### ISSUE THREAD

**Issue by msradam** [grafana/k6#2888]
### Feature Description

Golang is now supported on IBM z/OS, which allows Golang code to be compiled and run on a Unix System Services shell (i.e. z/OS's version of Unix). This also means that existing Golang programs like k6 can be ported to z/OS and run natively on the platform. k6 would be an especially valuable tool for load testing APIs on real z/OS hardware. 

I am interested in providing a compatibility update through updating specific build flags so that k6 can be built on z/OS "out of the box". 

An example: https://github.com/spf13/afero/pull/384
Here, I have submitted a PR to add `zos` build flags to afero, allowing it to be installed on z/OS. 

I would also be glad to follow up on other updates needed so that k6 could be considered 'officially' supported on z/OS Unix.

### Suggested Solution (optional)

I have already tested a simple compatibility fix by updating `cmd/ui_unix.go`
https://github.com/msradam/k6/blob/feature/zos-port/cmd/ui_unix.go

Along with the afero changes, this update allows k6 to run on z/OS. I would be glad to open a pull request, or make additional changes if necessary.

### Already existing or connected issues / PRs (optional)

#2892

**Comment by na--** [comment]
We'd be open to PRs for z/OS compatibility, especially if they as minor as adding a few build tags. Anything more involved could be subject to further discussion :sweat_smile: 

And, to be clear, at this point we don't intend to offer official z/OS builds or packages, run automated tests, or in any way guarantee  z/OS compatibility on our side. Someone else will need to do that, we are just willing to accept minor patches that help you out so that ideally you won't need to fork the whole project.

**Comment by msradam** [comment]
Thank you for the response! I have created the PR and it is, as you said, minor tags for compatibility so I can clone the main project directly for future builds. 

I would to glad to document the process of compiling and running tests for it for z/OS even if there are no plans for official compatibility. I appreciate your clarity.
