### ISSUE TITLE
async setup does not create the data object

### ISSUE THREAD

**Issue by Lukemufc91** [grafana/k6#2935]
### Brief summary

When using the async version of setup() the return value of the function call does not create the data object that should be passed in to the default function.

If you change back to a non-async setup call then the data object is set correctly.

### k6 version

0.44

### OS

Mac OS 13.1

### Steps to reproduce the problem

export async function setup() {
    return {data: "Arbitrary value here"}
}

export default function (data) {
    console.log(data)
}

### Expected behaviour

The data object is created and the console log would display an object { data: "Arbitrary value here" }

### Actual behaviour

The console log will display an empty object.

**Comment by mstoykov** [comment]
It also is a very old bug as this has been the case from when we have promises and event loop so almost a year since [v0.37.0](https://github.com/grafana/k6/releases/tag/v0.37.0). 

After all `async` means:
1. this will return a promise
2. you can use `await` inside the body

Here only number `1` is true and have been possible since we have Promises. The event loop just added ways for there to be stuff working on the result *off* the event loop. And now the `async`/`await` keywords support give us more ergonimic way to do this. 

To expand on @imiric workaround - I expect that you care about the result and it comes from an asynchronous call - let's say `http.asyncRequest`. In that case you will need to return an object and set a property of it in the `.then` so something like.
```javascript 
import http from "k6/http"

export function setup() {
  let result = {}
  innerSetup(result).then((res) => result.data=res)
  return result 
}

async function innerSetup() {
  let res = await http.asyncRequest("GET", "https://httpbin.test.k6.io/links/2/2")
  return res.body
}

export default function (data) {
  console.log(data.data)
}
```


As you can see you can even use `async` function within ;)

**Comment by Lukemufc91** [comment]
Thanks @mstoykov interestingly I had tried using the .then() with a non async setup already and received no result as I was passing back the resulting data string directly, encapsulating it in an object as you suggested worked perfectly.
