### ISSUE TITLE
default values for K6 are undefined

### ISSUE THREAD

**Issue by mehrad-rafigh** [grafana/k6#2936]
### Brief summary

We are currently setting up K6 for load, stress, soak and smoke testing our microservices with Nestjs

The tests are written with typescript and we use esbuild to bundle them to CJS.

I need to pass in a few environment variables to a docker container. 

```typescript
export const VUS = Number.parseInt(`${__ENV.VUS}`) ?? 1;
export const DURATION = `${__ENV.DURATION}` ?? "1m";
export const HTTP_REQ_DURATION = `${__ENV.HTTP_REQ_DURATION}` ?? "p(99)<100";
export const HTTP_REQ_FAILED = `${__ENV.HTTP_REQ_FAILED}` ?? "rate<0.01";
```
When I run the docker container with the environment variables everything works as expected.

But when I don't provide the environment variables K6 outputs the following error

### k6 version

latest

### OS

macOS 13.2

### Docker version and image (if applicable)

podman version 4.4.1

### Steps to reproduce the problem

Use example from [K6 page for a smoke test](https://k6.io/docs/test-types/smoke-testing/)

```typescript
import http from "k6/http";

import { check, sleep } from "k6";

export const VUS = Number.parseInt(`${__ENV.VUS}`) ?? 1;
export const DURATION = `${__ENV.DURATION}` ?? "30s";
export const HTTP_REQ_DURATION = `${__ENV.HTTP_REQ_DURATION}` ?? "p(99)<1500";
export const BASE_URL = `${__ENV.BASE_URL}` ?? "https://test-api.k6.io";
export const USERNAME = `${__ENV.USERNAME}` ?? "TestUser";
export const PASSWORD = `${__ENV.PASSWORD}` ?? "SuperCroc2020";

export const options = {
  vus: VUS, // 1 user looping for 1 minute

  duration: DURATION,

  thresholds: {
    http_req_duration: [HTTP_REQ_DURATION], // 99% of requests must complete below 1.5s
  },
};

export default () => {
  const loginRes = http.post(`${BASE_URL}/auth/token/login/`, {
    username: USERNAME,
    password: PASSWORD,
  });

  check(loginRes, {
    "logged in successfully": (resp) => resp.json("access") !== "",
  });

  sleep(1);
};
```

```javascript
import esbuild from "esbuild";
import glob from "tiny-glob";

const entryPoints = await glob("./src/**/*.ts");

const buildOptions = {
  entryPoints,
  bundle: true,
  minify: false,
  keepNames: true,
  outdir: "./dist",
  platform: "node",
  external: ["k6/http", "k6"],
};

await esbuild
    .build({
      ...buildOptions,
    })
    .then(() => console.log("⚡ Javascript build complete! ⚡"))
    .catch(() => process.exit(1));
```

```bash
docker run --rm -i grafana/k6 run - <dist/testing/k6-environment-var.test.js
```

```bash
➜ docker run --rm -i grafana/k6 run - <dist/testing/k6-environment-var.test.js             
WARNING: image platform ({amd64 linux  [] }) does not match the expected platform ({arm64 linux  [] })

          /\      |‾‾| /‾‾/   /‾‾/   
     /\  /  \     |  |/  /   /  /    
    /  \/    \    |     (   /   ‾‾\  
   /          \   |  |\  \ |  (‾)  | 
  / __________ \  |__| \__\ \_____/ .io

time="2023-02-18T15:14:15Z" level=error msg="could not initialize '-': could not load JS test 'file:///-': json: unsupported value: NaN"
```

### Expected behaviour

If environment variable is not provided through the `-e` flag the default value should be used

### Actual behaviour

If environment variable is not provided through the `-e` flag the value is undefined and the test crashes
```[tasklist]

```

**Comment by imiric** [comment]
Hi, thanks for opening this issue.

You're getting that error because of this line:

```javascript
export const VUS = Number.parseInt(`${__ENV.VUS}`) ?? 1;
```

If you don't set the `VUS` env var, then this will become `Number.parseInt("undefined")`, which will evaluate to `NaN`, and cause the `json: unsupported value: NaN` when you try to set it as the `vus` option value.

What you should instead do is this:

```javascript
export const VUS = Number.parseInt(__ENV.VUS ?? 1);
```

This will evaluate as you expect it, and work even if you don't set the `VUS` env var.

There is a related issue here, since k6 doesn't support the [nullish coalescing operator](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Operators/Nullish_coalescing), even though it's [supported in goja](https://github.com/dop251/goja/issues/382). @mstoykov mentioned in #2524 that this is because of Babel, but I'm not sure we will look into this, as we're considering dropping Babel soon, so this shouldn't be an issue for long. Regardless, this is not an issue in your case, since you transpile from TypeScript, where it's converted into a ternary operator, which k6 does support.

I'll close this since it's an issue with your script.

**Comment by mehrad-rafigh** [comment]
Thanks @imiric! Looking at the dist output from esbuild the nullish coalescing operator is not turned into a ternary operator. I will change that. And again thanks for responding! Much appreciated
