### ISSUE TITLE
Unable to view actual VU load for each scenario when running multiple scenarios

### ISSUE THREAD

**Issue by pranatikolla** [grafana/k6#2945]
### Brief summary

Hello,

we're unable to view the actual VU load that is being generated for each scenario when a test with multiple scenarios is run. This does not let us identify the right pattern that has actually been generated for each scenario. 

For e.g. if I have two test scenarios, each with user load 2 and 2, the individual scenario VU graphs that are charted show a total of 4 and not 2.

### k6 version

0.42.0

### OS

NA

### Steps to reproduce the problem

Set up two scenarios with 2 VUs load each and run a test. Once the test is over, try to pull out graphs for VU load against each scenario. 

### Expected behaviour

if I have two test scenarios, each with user load 2 and 2, the individual scenario VU graphs that are charted show a total of 4 VUs

### Actual behaviour

The individual graphs should show 2 VUs each.

**Comment by na--** [comment]
The `vus` metric unfortunately isn't tagged by `scenario` because it considerably predates scenarios :sweat_smile: At this point we can't change that behavior without a major breaking change, but we can probably add a new metric to track VUs per scenarios. There is already an open issue about that, https://github.com/grafana/k6/issues/1833, so I'll close this one in favor of it.

As a better alternative and a workaround until that issue is implemented, I'd suggest graphing another metric that represents the the actual load (e.g. `http_reqs`) instead of trying to use `vus`. It is going to be tagged per scenario and will be much more realistic than trying to correlate VUs with the load. After all, one VU can do one request and `sleep()` for an hour while another VU does a 100 requests every second with `http.batch()`.

**Comment by pranatikolla** [comment]
This has also been raised here on the suggestion of Alex and Pawel. 
Thanks for the issue reference and suggestion but the VU tracking will be more helpful since our requirements are defined based on VUs on the system. Will wait for the feature release :)
