### ISSUE TITLE
Include group in check metrics

### ISSUE THREAD

**Issue by michael-sw-id** [grafana/k6#2980]
### Feature Description

Currently metrics for checks are generated as `k6.check.expected_Expect_HttpStatus_to_equal_201.pass`

It would be great if metrics include the group e.g.

`k6.check.group_create_customer.expected_Expect_HttpStatus_to_equal_201.pass`

Ideally should also support nested groups e.g.

- Onboard customer journey
      - Submit Identity Card
      - Register Password
      - Accept T&C

### Suggested Solution (optional)

Given this is a breaking change for existing dashboards or consumers of these metrics, would probably need to put it behind some feature flag/configuration.

**Comment by imiric** [comment]
Hi there, thanks for opening this issue.

Judging by the metric name, I assume you're using the `statsd` output, right? Are you sending metrics to Datadog or New Relic?

While this seems like a useful suggestion, it needs some evaluation, so we're unlikely to implement it anytime soon.

For one, it would be a breaking change for users who don't expect to have group names in check metrics. This could be mitigated by making the behavior optional, but we wouldn't want to complicate the configuration any further.

Also, we're currently evaluating the [status and future of StatsD outputs](https://github.com/grafana/k6/issues/2982), and we might decide to make individual backend extensions, or deprecate support for it altogether. Since it's in a state of flux, it's unlikely we'll make any changes to it while it remains part of k6.

So we'll keep this issue open and look into it, but no guarantees it will be implemented.

**Comment by michael-sw-id** [comment]
yep, statsd with datadog

**Comment by nilesh05apr** [comment]
Hi @imiric can i try this? 

To implement this change, we can introduce a new configuration option in k6 that enables this feature. For example, we can add a flag like --enable-check-groups that would modify the metric names to include the group information.

I am not sure about the nested subgroups right now. But we can proceed similarly for them as well. 
Please let me know what are your thoughts on this.

**Comment by imiric** [comment]
@nilesh05apr Thanks for offering to help, and feel free to work on it in your k6 fork, but we're not likely to merge any changes to the `statsd` output because of what I mentioned above. Adding a new CLI flag would also be problematic because of #883.

**Comment by LeonAdato** [comment]
Per [@olegbespalov](https://github.com/olegbespalov) and  [@javaducky](https://github.com/javaducky), this issue should probably be part of the StatsD project. Feel free to transfer it here: 

[https://github.com/LeonAdato/xk6-output-statsd](https://github.com/LeonAdato/xk6-output-statsd)
