### ISSUE TITLE
Script formatter

### ISSUE THREAD

**Issue by craigpastro** [grafana/k6#2992]
### Feature Description

👋 The only time I write Javascript is when I am writing k6 scripts. I was just thinking it would be pretty cool if there was a command to format these scripts. Something like `k6 fmt script.js`. I know there is ESLint and others, and that people in the JS world each have their own preferences, but it would be awesome for people like me who want an opinionated formatter.

Thanks for listening! k6 is awesome ❤️ 

### Suggested Solution (optional)

Create a command `k6 fmt` which wraps ESlint with a highly opinionated config.

**Comment by craigpastro** [comment]
I just discovered https://prettier.io/, so there is that.

**Comment by na--** [comment]
@craigpastro, thank you for opening this issue! Unfortunately, it's very unlikely that we'll ever add a `k6 fmt` sub-command.

There isn't a single accepted standard for formatting JavaScript code, not in the same way that we have `go fmt` for example. There also isn't anything special about k6 JavaScript tests compared to other .js scripts that would necessitate a custom linter or formatter. Plenty of tools like ESLint and Prettier can already do these jobs well enough, so there is very little value to build into k6 and maintain another tool like that... Besides, formatting and linting code these days is mostly the responsibility of text editors and IDEs, which already work well enough with existing tools, and if we add a `k6 fmt` sub-command, it's likely that users will also want us to develop these editor integration as well...

Instead of a new sub-command, it's much more likely that we can provide some officially recommended eslint and prettier configurations (or something like that) and instructions how to make use of them.  We can use them in our [docs](https://k6.io/docs/), [jslib.k6.io](https://jslib.k6.io/), and [the script editor in k6 cloud](https://k6.io/docs/cloud/creating-and-running-a-test/script-editor/). 

So, I'll close this issue in favor of https://github.com/grafana/k6-docs/issues/192, which more closely resembles the idea above.

**Comment by craigpastro** [comment]
👋 @na-- Thanks so much for the explanation. That makes a lot of sense. Actually, with the discovery of prettier I am pretty satisfied. Before that, I was trying to set up ESLint and there were too many options that got quite annoying.

Anyway, thanks for your response!
