### ISSUE TITLE
How to read the text content as an array

### ISSUE THREAD

**Issue by h2yong** [grafana/k6#2993]
### Brief summary

How to read the text content as an array

### k6 version

v0.43.1

### OS

windows10

### Steps to reproduce the problem

How to read the text content as an array

### Expected behaviour

I can read the txt file to an array。
const a_array = open('a.txt');

the a_array is an array

### Actual behaviour

I don't know How do it

**Comment by na--** [comment]
Please don't ask questions in GitHub issues, use the community forum for that: https://community.k6.io/

In your case, I assume you want to split your text file by lines, and have one line per array item? If so, you can use the [`String.split()` JavaScript function](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/String/split) for that, somewhat like this:
```js
 const a_array = open('a.txt').split('\n');
```

Just keep in mind that every VU will have a copy of that file in memory. So, if it's a big file, that will use a lot of memory, so you might want to use something like [k6's `SharedArray`](https://k6.io/docs/javascript-api/k6-data/sharedarray/) instead of a normal JavaScript array instead.
