### ISSUE TITLE
handleSummary do not check if directory exists

### ISSUE THREAD

**Issue by fenchu** [grafana/k6#3084]
### Brief summary

If I forget to create my output directory, runs will fails in the after-stage when creating summary.

Nice to have a way to verify this upfront that output dir is missing if you have set it.

Just add some simple example how to verify this.

### k6 version

0.44.1

### OS

windows 11

### Steps to reproduce the problem

Use a handleSummary like this:

```
export function handleSummary(data) {
  const extras = Object.assign(
    {
      testenv: testenv,
      tenant: tenant
    },
    data
  );
  return {
    "./report/result.html": htmlReport(data),
    stdout: textSummary(data, { indent: " ", enableColors: true }),
    "./report/result.xml": jUnit(data),
    "./report/summary.json": JSON.stringify(extras, null, 2)
  };
}
```

If I forget to create `results` before I run I loose the summary:

```
:
    vus_max........................: 50     min=50      max=50
ERRO[0011] failed to handle the end-of-test summary      error="Could not save some summary information:\n\t- could not open './report/summary.json': open ./report/summary.json: The system cannot find the path specified.\n\t- could not open './report/result.html': open ./report/result.html: The system cannot find the path specified.\n\t- could not open './report/result.xml': open ./report/result.xml: The system cannot find the path specified."
```

### Expected behaviour

Create the summary files

### Actual behaviour

crash and no summary files

**Comment by imiric** [comment]
Hi, thanks for creating this issue.

> Nice to have a way to verify this upfront that output dir is missing if you have set it.

The thing is that `handleSummary()` is only called when the test ends, because it receives the metric summary data of the entire test. We can't really call it upfront, since the generated data would not make sense. This means that we can't know the output paths upfront either.

What we can do is create the parent directories if they don't exist yet, like `mkdir -p` would do, before we write the file. Would this help?

**Comment by fenchu** [comment]
that would be great, as long as we can find the summary files. our ci/cd system really like to find the files in a separate directory.

**Comment by urugator** [comment]
> create the parent directories if they don't exist yet, like mkdir -p would do, before we write the file

I would appreciate that as well. I would like to output summary to some something like `./tmp/summary.json` or even `./tmp/<test_id>/summary.json`, but it seems the only way to do that atm is using xk6-file extension, which is a bit more complicated than I would expect.

**Comment by oleiade** [comment]
We have discussed this topic in the context of #3464 relatively recently, and we concluded that we probably won't unless there are additional specific and concrete needs for k6 to do that itself.

This was because users should already be able to run `mkdir -p directory-hierarchy` before `k6 run` to ensure the folders where they intend to write test results exist.

Closing this for now. If you have a specific use case that can not possibly be solved by using the `mkdir -p` workaround, please feel free to reopen with a detailed explanation 🙇🏻
