### ISSUE TITLE
Installing socket.io-client with webpack

### ISSUE THREAD

**Issue by mjaliz** [grafana/k6#3113]
### Feature Description

I want to use the socketio client wtih k6. I have installed the socket.io-clinet with webpack and build a [name].bundle.js file.
But the problem is here, when I use 'web' for 'target' key in webpack config file, I get this error: document is not defined, and I know that node dose not have access to document. when I change the 'target' value to 'node', I get 'fs' error.
How can I fix this issue?
Thanks for your attention.

**Comment by imiric** [comment]
Hi, please search the issues before opening a new one.

Support for socket.io was already discussed in #1306, and there's a JS implementation that uses xk6-websockets [here](https://github.com/grafana/xk6-websockets/issues/34).

The reason you're getting those errors is because k6 does not use a browser or Node JS runtime, so some JS libraries that target these won't work in k6. See [the documentation](https://k6.io/docs/#what-k6-does-not).
