### ISSUE TITLE
Unale to execute scenarios in linux

### ISSUE THREAD

**Issue by siva201014** [grafana/k6#3126]
### Brief summary

I am able to execute below script format in windows 
export const options = {

    thresholds: {},

    scenarios: {

      Scenario_1: {

        executor: 'shared-iterations', //Each VU executes an exact number of iterations. The total number of completed iterations will be vus * iterations. (uses vus, iteration, and duration)

        gracefulStop: '30s',

        vus: 100,

        iterations: 100,

        maxDuration: '20m',

        exec: 'scenario_1',

      },

    },

  }  export function scenario_1() {}

but not in linux.

both are in k6 v0.44.1

### k6 version

0.44.1

### OS

linux

### Steps to reproduce the problem

just run above script

### Expected behaviour

It should run successfully.

### Actual behaviour

getting nof default export funcion found error.

**Comment by imiric** [comment]
Your script runs fine for me on Linux, so you have another issue. I'm guessing that you're not actually running this exact script on Linux in order to get the `nof default export funcion found` error. Make sure that you're actually defining and exporting the `scenario_1` function, and that it's referenced correctly in the `exec` property.

Also, please don't create issues unless you're absolutely certain it's a bug. See the [support document](https://github.com/grafana/k6/blob/master/SUPPORT.md). If such a simple script would trigger a bug on Linux, we would've already noticed it. Instead, search the community forum and post it there first to get support from the community.
