### ISSUE TITLE
Use a dedicated option instead of MaxMetricSamplesPerPackage

### ISSUE THREAD

**Issue by codebien** [grafana/k6#3156]
### What

As defined by the code's comment below, we should use a better name that matches the purpose for `MaxMetricSamplesPerPackage` in `cloudv2`.

`cloudv2` uses `MaxMetricSamplesPerPackage` for defining the max number of time series in a single flush batch. Instead, the current option defines the number of k6 samples.

https://github.com/grafana/k6/blob/1df72a0a1b23d7b0827813f6b709c7ad7bb4193b/cloudapi/config.go#L34-L36

https://github.com/grafana/k6/blob/1df72a0a1b23d7b0827813f6b709c7ad7bb4193b/output/cloud/expv2/output.go#L110-L112

### Why

`MaxMetricSamplesPerPackage `is inherited from v1 but we should use a cleaner and dedicated field.

### Suggestion

Add a dedicated new field for defining the max number of series in a single flush batch.

**Comment by imiric** [comment]
Whatever the new name is, it shouldn't reference "packages", which I'm not sure what they are. I think this was meant to be "per (network) _packet_", but even that would be wrong, as HTTP is not concerned with TCP/IP packets, and requests could be split over several packets. So "per (HTTP) request" would be more accurate, or since the v2 output now deals with protobuf, maybe "per (protobuf) message", or more generically "per payload", would be better.
