### ISSUE TITLE
SharedArray VU receives environment variable set by scenario

### ISSUE THREAD

**Issue by amommersteeg-d2l** [grafana/k6#3362]
### Feature Description

It doesn't look like the the environment variable set by scenario are passed into the SharedArray VU. For example
```
env: { DISABLE_SETUP: 'true' }
```
The SharedArray **does** receive the ENV from the console input `-e DISABLE_SETUP=true`.

A use case to pass the scenario set EVN into the SharedArray is when multiple scripts designed to run independently are combined into a scenario. But only need the setup to run once.  Here is a simple example were we run `test.js` and don't want the SharedArray to run setup in the `main.js` script. 

```
// test.js
import * as generateScript from './generate.js';
import * as testScript from './main.js';

export const options = {
    scenarios: {
        generate_scenario: {
            exec: 'runGenerate',
            executor: 'per-vu-iterations',
            vus: 1,
            iterations: 1, 
        },
        test_scenario: {
            exec: 'runTest',
            executor: 'per-vu-iterations',
            vus: 1,
            iterations: 1,
            env: { DISABLE_SETUP: 'true' }
        }
    }
};


export function runGenerate() {
    generateScript.default();
}

export function runTest() {
    testScript.default();
}
```

```
// generate.js
import { SharedArray } from 'k6/data';

new SharedArray('generate', function() {
    if (!__ENV.DISABLE_SETUP) {
        console.log("Shared - generate.js")
    }

    return ['a']
})

export default function(){
    console.log("Test - generate.js")
}
```

```
import { SharedArray } from 'k6/data';

new SharedArray('main', function() {
    if (!__ENV.DISABLE_SETUP) {
        console.log("Shared - main.js")
    }

    return ['a']
})

export default function(){
    console.log("Test - main.js")
}
```

Currently see 
```
INFO[0000] Shared - generate.js                          source=console
INFO[0000] Shared - main.js                              source=console
INFO[0000] Test - generate.js                            source=console
INFO[0000] Test - main.js                                source=console
```

Expect to see
```
INFO[0000] Shared - generate.js                          source=console
INFO[0000] Test - generate.js                            source=console
INFO[0000] Test - main.js                                source=console
```

**Comment by mstoykov** [comment]
Hi @amommersteeg-d2l, thanks for reporting this :bow:.

Unfortunately due to architectural decisions this is not possible, but also luckily .. not needed for your case :thinking:.

So first, VUs are not for a given scenario they are shared between scenarios and might *or* might not be used in multiple scenarios. But their initialization code (the one outside of functions) needs to be run so ... we have initialize them.

This happens though before they are part of any specific scenario, and it might be that they are in multiple ones, so it will be impossible to know which scenario specific __ENV should be used. Which is why it only uses the specific ones when running the `default` functions.


On the other hand with your use of [`SharedArray`](https://k6.io/docs/javascript-api/k6-data/sharedarray/) - there is no reason for that.

The whole point of a `SharedArray` is that it's initialization function is called *once* per k6 process and then the results are shared between all VUs.

So if you want to use a `SharedArray` in one of the scenarios but not the others - just ... do that. There is no real problem or benefit to not having the `SharedArray` in the other.

On the other hand if you want the `SharedArray` to have two different values - you must make two separate `SharedArrays` and use the correct one in each scenario.

I will close this as we are extremely unlikely to "fix"/change this. Please for more usage discussion use the [community forum](https://community.grafana.com/)

**Comment by amommersteeg-d2l** [comment]
Thank you some much for taking the time to write this explanation of why this won't work, it make perfect sense.
