### ISSUE TITLE
K6 contradicts itself in iteration statistics

### ISSUE THREAD

**Issue by gdevelek** [grafana/k6#3377]
### Brief summary

I have a test that starts with a Keycloak authentication call within the setup() function. Each iteration contains a single request. 

At the end K6 reports 48 iterations and 49 requests, as it should. I.e. it doesn't count the Keycloak request as an iteration.

However, in the iteration duration statistics, the minimum value is exactly the duration of the Keycloak request. 

In other words, K6 contradicts itself. In the iteration count, the Keycloak request is not treated as an iteration. In the stats, it is.

The Keycloak request ought not to be part of the iteration duration statistics. Or even the http request statistics. It's just a  preparatory step. It's not Keycloak that I'm testing here.

![image](https://github.com/grafana/k6/assets/8545060/f87227fd-b165-4af3-9ea4-c9107ec38f9d)

![image](https://github.com/grafana/k6/assets/8545060/cf6d9265-6a96-4e33-99ad-beab452eaeeb)

### k6 version

0.45.0

### OS

WSL2 Ubuntu 20.04

### Steps to reproduce the problem

run a test that starts with a Keycloak authentication call, inside a setup() function

### Expected behaviour

The Keycloak call should not be counted as an iteration and contribute to the iteration duration stats. 

### Actual behaviour

The Keycloak call is not counted as an iteration BUT contributes to the iteration duration stats.

**Comment by oleiade** [comment]
Hi @gdevelek 👋🏻 

Thanks a lot for bringing this to our attention 🙇🏻 

My understanding of what you're pointing at is that you observe the execution of your `setup` function being considered in the `iterations_duration` metric but not in the `iterations` metric.

If my interpretation is correct, then it is the currently expected behavior of k6. You can read more about it and its workaround in the [documentation](https://k6.io/docs/using-k6/workaround-to-calculate-iteration_duration/).

We are, however, aware of this issue and are tracking it in #1605. We have yet to estimate a time for its resolution, though.

Based on my assumption that my understanding is correct, this is a duplicate, and I will label it accordingly for the original issue.
