### ISSUE TITLE
Support field_mask.proto for GRPC

### ISSUE THREAD

**Issue by LeonhardtCKL** [grafana/k6#3426]
### Brief summary

When using k6 to execute gRPC, it fails to parse proto files with `field_mask.proto`.

throw error is:
```
ERRO[0000] GoError: unable to serialise request object to protocol buffer: proto: syntax error (line 1:75): unexpected token {
        at reflect.methodValueCall (native)
```

### k6 version

v0.47.0 

### OS

Windows 11

### Steps to reproduce the problem

proto is:
```
syntax = "proto3";

package test;

import "google/protobuf/empty.proto";
import "google/protobuf/field_mask.proto";

service TestService{
  rpc ListTest(Request) returns (google.protobuf.Empty);
}
message Fence{
  string id = 1;
  string name = 2;
}
message Request {
  Fence fence = 1;
  google.protobuf.FieldMask update_mask = 2;
}
```

source [test.js] is:
```
import { Client, StatusOK } from "k6/experimental/grpc";
import { check, sleep } from "k6";

const client = new Client();

client.load(["./proto"], "dokokana/test.proto");

export default () => {
  const req = {
    fence: {
      id: "01HDQM85YMSZP1E51YQ221S1RN",
      name: "Hello",
    },
    update_mask: {
      paths: ["name"],
    },
  };
  client.connect("localhost:8080", { plaintext: true });
  const response = client.invoke("test.TestService/ListTest", req);
  check(response, {
    "status is OK": (r) => r && r.status === StatusOK,
  });
  sleep(1);
};

export function teardown() {
  client.close();
}
```

Run Command: `k6 run test.js`

### Expected behaviour

running success

### Actual behaviour

throw err:
```
ERRO[0000] GoError: unable to serialise request object to protocol buffer: proto: syntax error (line 1:75): unexpected token {
        at reflect.methodValueCall (native)
```

**Comment by mstoykov** [comment]
Hi @LeonhardtCKL, sorry for the slow reply, but I hit a road block while lookign at this.

At this point I am still not certain what exactly is happening - but I can reproduce your problem.

Having taken a bunch of time looking at old issues and code - it seems to me like you are using the fieldmask ... wrongly.

It seems like instead of it having to be an object with `paths` inside it is a string with comma separated paths *inside* of it.

```javascript
const req = {
    fence: {
      id: "01HDQM85YMSZP1E51YQ221S1RN",
      name: "Hello",
    },
    update_mask: "name,anotherone",
  };
```

You can clearly see this in this documentation on [json encoding of field masks](https://protobuf.dev/reference/protobuf/google.protobuf/#json-encoding-field-masks)

With that I am not getting an error and the message is sent, but I don't have a service to test this with end to end.


Can you please test and if it works for you lets close this issue.

**Comment by LeonhardtCKL** [comment]
Thank you for your answer. It is working for me. I did not consider that it has a different format in JSON.

**Comment by mstoykov** [comment]
Okay then I will consider this resolved :tada:
