### ISSUE TITLE
Support of Uint64 ids in JSON requests/responses

### ISSUE THREAD

**Issue by arturk** [grafana/k6#3450]
### Feature Description

When a server responds with JSON that has its uid as Uint64 or you need to send a request with Json that contains such id k6 becomes a very inconvenient tool.
I would like k6 to be able to do parsing and converting to strings Json that look like
```
{
    ....,
    "item": {
            "id": 2733382000000000049
    }
    ....,
}
```
Because the id here is larger than the `MAX_SAFE_INTEGER` the k6 `response.json()` call loses the precision and converts id to `"id": 2733382000000000000` losing the last precision bits (that 0049).

**Comment by mstoykov** [comment]
Hi @arturk, thanks for reporting this :bow: 

The way [`JSON.parse`](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/JSON/parse) works is defined in the ECMAScript specification and that specification says that any numbers goes to the normal ECMAScript/javascript number representation - which is a float. 

Theoretically `response.json()` could return something more specific - but k6 currently does not support BigInt - so that isn't possible either.

Luckily for you the `JSON.parse` method does have a way to have custom parsing of data, and you can parse the `id` as *string* (or BigInt when k6 supports it or you polyfill it). Here is basic code based on the following code based on [this stackoverflow answer](https://stackoverflow.com/a/69644630/5427244):

```javascript
// source JSON string
const input = ` // changed from stackoverflow
{
    "item": {
            "id": 2733382000000000049
    }
}
`


// function that implements desired criteria
// to separate *big numbers* from *small* ones
//
// (works for input parameter num of type number/string)
const isBigNumber = num => !Number.isSafeInteger(+num)


// function that enquotes *big numbers* matching
// desired criteria into double quotes inside
// JSON string
//
// (function checking for *big numbers* may be
// passed as a second parameter for flexibility)
const enquoteBigNumber = (jsonString, bigNumChecker) =>
    jsonString
        .replaceAll(
            /([:\s\[,]*)(\d+)([\s,\]]*)/g,
            (matchingSubstr, prefix, bigNum, suffix) =>
                bigNumChecker(bigNum)
                    ? `${prefix}"${bigNum}"${suffix}`
                    : matchingSubstr
        )


// parser that turns matching *big numbers* in
// source JSON string to bigint
const parseWithBigInt = (jsonString, bigNumChecker) =>
    JSON.parse(
        enquoteBigNumber(jsonString, bigNumChecker),
        (key, value) =>
            !isNaN(value) && bigNumChecker(value)
                ? '"' + value + '"' // changed from stackoverflow
                : value
    )

// resulting output
const output = parseWithBigInt(input, isBigNumber)


console.log("output.item.id: \n", output.item.id, `(type: ${typeof output.item.id})`) // changed from stackoverflow
```

Depending on how big this json input is - you might also try a utility function such as [`findBetween`](https://k6.io/docs/javascript-api/jslib/utils/findbetween/) as it will be way faster then going through and parsing a json in this specific way.

Given the facts that:
1.  we can't change how `JSON.parse` works 
2. `k6/http` is currently in maintaince mode
3.  we can't make this transformation automatically as it changes a number to a string
4. we do not have BigInt to make it not loose


I will close this issue and hopefully anyone interested can find the above solution sufficing.
