### ISSUE TITLE
golangci-lint version format in macOS is different than expected in .golangci.yml

### ISSUE THREAD

**Issue by jsolana** [grafana/k6#3508]
### Brief summary

In macOS, `golangci-lint version` returns its  version in different format.

```console
golangci-lint version
golangci-lint has version 1.55.2 built with go1.21.3 from e3c2265 on 2023-11-02T21:40:02Z
```

Instead of `vMajor.minor.patch`. Eg using docker alternative:

```console
docker run --rm -v $(pwd):/app -w /app golangci/golangci-lint:v1.55.2 golangci-lint version

golangci-lint has version v1.55.2 built with go1.21.3 from e3c2265f on 2023-11-03T13:27:54Z
```

[`.golangci.yml`](https://github.com/grafana/k6/blob/master/.golangci.yml#L1) expects `v1.55.2` version format but `golangci-lint version` returns  `1.55.2` format in macOs then `make lint` prompts a warning:

```console
Your installation of golangci-lint is different from the one that is specified in k6's linter config (there it's v1.55.2). Results could be different in the CI.
```

## Possible solution

Remove the `v` from `.golangci.yml` to be macOs compatible (and still being compatible with other platform solutions).

 

### k6 version

0.48.0

### OS

ProductName:	macOS ProductVersion:	12.5.1 BuildVersion:	21G83

### Steps to reproduce the problem

Install `golangci-lint` following [the instructions to install `golangci-lint` locally in MacOs](https://golangci-lint.run/usage/install/#macos)

Run `make lint`

### Expected behaviour

No issues reported

### Actual behaviour

Internally [check-linter-version](https://github.com/grafana/k6/blob/0f204b9dbebaca11d286e11eaf8e114e26acf257/Makefile#L15) fails:

```console
Your installation of golangci-lint is different from the one that is specified in k6's linter config (there it's v1.55.2). Results could be different in the CI.
```

**Comment by jsolana** [comment]
Bad issue type

**Comment by jsolana** [comment]
Sorry, it should be an issue without bug label.

**Comment by codebien** [comment]
Hey @jsolana,
thanks for reporting this issue.

Your suggestion seems fine on our side. Are you interested in contributing with a pull request for it?

In any case, this sounds like a bug on `golangci-lint`, so it would be good to open an issue on the `golangci-lint` repo and link it in a comment in the code. Otherwise, in the future, it could be difficult to get the reason as the version seems to include the `v` as the release name.

**Comment by jsolana** [comment]
Make totally sense. I'll do it :)
Here is the [issue](https://github.com/golangci/golangci-lint/issues/4263) in golanci-lint repo

**Comment by codebien** [comment]
@jsolana considering the comments on the issue, it sounds like the fix should be applied to homebrew more than k6. An alternative for having it supported by macOS seems available through binaries.

The linter is heavily used across several projects, so I would like if we try fixing directly homebrew instead of doing it on k6.

It should be possible by adding the `v` prefix here https://github.com/Homebrew/homebrew-core/blob/56b593d11f0fadf7f63b0b437a5cb520c83489e1/Formula/g/golangci-lint.rb#L25.

**Comment by jsolana** [comment]
You are right!
Let's try it :D 
Thanks a lot for your guidance

**Comment by codebien** [comment]
Thanks for the opened issue on the Homebrew repo. I close this issue for now, feel free to re-open if you get a negative feedback or if you have more details to share.

I subscribed to the Homebrew issue so I will receive the updates and we will be aware of the progress.

**Comment by jsolana** [comment]
Info related: https://github.com/golangci/golangci-lint/discussions/4268
