### ISSUE TITLE
functions queued in eventLoop only run after the main function is done executing in a VU

### ISSUE THREAD

**Issue by onprem** [grafana/k6#3755]
### Brief summary

Due to how it is implemented internally, the main function is added as the first item in the `eventLoop` queue. Due to this, other functions added to the `eventLoop` during the execution will be only run after the main test function has exited.

https://github.com/grafana/k6/blob/f947acb0bc57957d04d8e2a151c573fdc978e65e/js/runner.go#L858-L861

This makes using long running VUs impractical in many use cases.

### k6 version

0.51.0

### OS

Arch Linux

### Steps to reproduce the problem

This can be reproduced by running a VU for a long duration where other functions are being added to the `eventLoop` queue, and observing when they execute.

A quick way to do that would be to use the test script I am working on here https://github.com/onprem/entity-store-loadtest

### Expected behaviour

I expected the `eventLoop` queue to be independent of the test function. Running the eventLoop in parallel would allow modules/users to rely on it when the test function also need to run for a long duration (like for full test duration).

### Actual behaviour

The functions added in the `evenLoop` queue are executed only after the test function has finished running.

I ran into this while trying to load test a gRPC API that exposes a stream of events. The callback functions defined by me in the script execute only after the main function ends (one iteration).
```js
stream.on('data', func(resp) {
  // process the message
  // calculate metrics for latency etc.
})
```

We need a long running VU/test function to receive all of the events. But the callback functions won't be called untile the end, due to this the latency metrics etc. are not usable. You can see in the screenshot below that the `watch_event_latency` metric only shows up in the end, with the latency being about same as the test duration itself.

![Screenshot_20240523_161100](https://github.com/grafana/k6/assets/29674758/5f9c708b-d27a-4f23-8f80-33f98fa0ade5)

**Comment by oleiade** [comment]
Added @mstoykov to the convo, as he will have more details to offer on the behavior of the event loop in k6 for sure 🙇🏻

**Comment by mstoykov** [comment]
The whole idea of an event loop (in the JS world) is for there to be only 1 thing executing JS code and for the majority of the work to happen *off* it.

The fast version is that:
1. JavaScript/ECMAScript is *single* threaded - you can't run more than 1 line of js code even if you wanted to at a time.
2. the main loop is usually there to setup a bunch of *asynchronous* operations and then they will do the "hard work" off the event loop. Only running on it in order to synchronize results back.
3. Given the above you should be using asynchronous APIs not the synchronous ones and potentially using `async`/`await` syntax. So no `sleep` - use `setTimeout` or [`delay` polyfill](https://gist.github.com/mstoykov/7684bf54a1e2f35d048868ba6117e2cb), no `http.request` - use `http.asyncRequest` or in your case [`asyncInvoke`](https://grafana.com/docs/k6/latest/javascript-api/k6-net-grpc/client/client-async-invoke/)


Hope this is helpful but I am closing this as this is exactly how the event loop ~should~ must work . Please if you have more usage questions ask them in the [community forum](https://community.grafana.com/c/grafana-k6/70)
