### ISSUE TITLE
Slack/Discord support

### ISSUE THREAD

**Issue by Romarionijim** [grafana/k6#3887]
Hello all, does k6 have slack or discord support channel? if not, how do we get support from community other than fourms?

**Comment by codebien** [comment]
It is linked in the [Support](https://github.com/grafana/k6/blob/master/SUPPORT.md) page. Pleas, remember to use the search feature before opening a new issue.

**Comment by Romarionijim** [comment]
The issue was opened to the broken link in the page you referred me to :) I asked specifically if there is slack or discord

**Comment by mstoykov** [comment]
@Romarionijim can you explain why you prefer to have discord/slack than using the forum?

**Comment by Romarionijim** [comment]
@mstoykov in my experience with other tools that have a slack or discord it is much easier to get help especially when stuck when you are new to a tool like k6 instead, it is more modern and engaging and faster.

**Comment by mstoykov** [comment]
My and the team experience is that we get the same questions over and over again and as slack doesn't have retention we keep giving the same answers.

So the k6 team does *not* respond to questions and AFAIK most are not even logged into the slack.
Additionally, slack is not searchable through google - so you always need an account in order to get any info out of it. Which is one more reason why the team decided to move away from slack support years ago at this point.

There definitely are still people using it, and there are a bunch of people answering questions. But just scrolling up - a bunch of the questions aren't answered and likely googling them will lead you to the community forum with an answer and explanation.
