### ISSUE TITLE
xk6-temporal

### ISSUE THREAD

**Issue by ameetpal** [grafana/k6#3942]
We are trying to xk6-temporal but the repo is archived but repo is forked by @mstoykov , so is anyone maintaining it, 
If we start development on it where should we push the code in our repo or archived one.

**Comment by mstoykov** [comment]
Hi @ameetpal - no the repo isn't maintained.

I have a fork of most extensions repos as over time I have done some mass PRs through a set of [scripts](https://github.com/mstoykov/xk6-extensions) - usually to keep them working.

I am definitely not maintaining any of them.

Unfortunately github doesn't make it easy to delete 30-40 repositories, so I just leave them around until the next mass update. 

> If we start development on it where should we push the code in our repo or archived one.

I don't see how you can push to the archived one and I am not maintaining this, so I would recommend you own fork.

Hope this helps you, and I will delete this particular repo.

**Comment by ameetpal** [comment]
Which name should we take, are we planning to delete Original xk6-temporal repo ?

**Comment by mstoykov** [comment]
I am not the original contributor and can't delete the original repo. I also don't intend on actually developing this extension.

Again I just made a mechanical fix with a script and made PRs to every extension. 

If you want you are free to fork it and keep the name `xk6-temporal` or .. not.

You might want to contact the original developers on this, instead of me :)
