### ISSUE TITLE
Difference in behavior between v0.53.0 and v0.52.0

### ISSUE THREAD

**Issue by khamdocs** [grafana/k6#3981]
### Brief summary

Variables defined and exported from common library were extensible in 0.52.0, but are not in 0.53.0. An error is generated when the script attempts to change the value of a variable exported by an included js file to a new value.

ERRO[000] TypeError: Cannot add property myVar, object is not extensible
        at default (file:///home/nccloud/test_3/main_script.js:37:52(10)) executor=per-vu-iterations scenario=pervuiterations source=stacktrace

### k6 version

0.53.0

### OS

Linux Ubuntu 20.04.6 LTS

### Docker version and image (if applicable)

N/A

### Steps to reproduce the problem

Unzip the attached file, run "run.sh" script on k6 v0.53.0

[test3.zip](https://github.com/user-attachments/files/17341922/test3.zip)

### Expected behaviour

Previously no error was generated on v0.52.0
![Image](https://github.com/user-attachments/assets/ebb0ab26-54fd-4aa0-a546-db20aba00130)

### Actual behaviour

Error is seen as attached![Image](https://github.com/user-attachments/assets/44b4a519-40df-4ac5-a8fa-c56391a8723d)

**Comment by joanlopez** [comment]
Hi @khamdocs,

I'm sorry for the confusion it may have caused, but this is a good example of:
_- It's not a "bug", it's a feature_

If you take a look at [v0.53 release notes](https://github.com/grafana/k6/blob/master/release%20notes/v0.53.0.md), you'll notice that one of the main features introduced in that release (and a breaking change, as you have experienced) is [support for native ECMAScript modules](https://github.com/grafana/k6/blob/master/release%20notes/v0.53.0.md#ecmascript-modules-esm-native-support-related-breaking-changes).

As per spec (ES6), the namespace of an import (the `*` in the import) is a read-only, immutable object (_[here](https://github.com/microsoft/TypeScript/issues/2456) you can see a related issue in the Typescript repository, from some years ago_). So, if you want to keep the same behavior since v0.53, you'll need to do it in a different way.

**Option 1:** Use `globalThis`

```js
// Either at the beginning of your script, or in an imported file:
globalThis.myVar = "defaultValue"

// Later in the code:
if (typeof __ENV.my_var !== 'undefined') {
  globalThis.myVar = __ENV.my_var;
}

// Then use `globalThis.myVar`, as needed.
```

**Option 2:** Define your own global object

```js
// myGlobal.js
let myGlobal = {
  myVar: "defaultValue"
}; 

export default myGlobal;

// From the script file:
import myGlobal from "./myGlobal.js"

if (typeof __ENV.my_var !== 'undefined') {
  myGlobal.myVar = __ENV.my_var;
}
```

Beyond that, there are other possible workarounds, as exposing a "setter" function from the package where `myVar` is exported from. However, with the minimum example that you shared (thanks for making it so easy to reproduce 🙌🏻 ), it's difficult to fully get what's your purpose and what would be the most recommended approach.

Feel free to close the issue if that's enough. If not, and none of the ones above works for you, please tell us more about your needs, and we'll be happy to help.

Thanks! 🙇🏻

**Comment by khamdocs** [comment]
Thanks for your reply @joanlopez 

The minimal example I gave to reproduce the problem is trivial, however the issue we have is there are dozens of test scripts that were written exploiting this feature to basically export many variables with default values and override them if such an override was set in the environment.

It seems one way or the other we will have to rewrite the scripts to do something along the lines of 1 or 2.

However one possible issue that I see with using globals to fix this - and I could be misunderstanding here - is that we use the __VU and __ITER variables to divide and conquer a range, so that we are not creating/updating/deleting the same data in the many concurrent instances of the VU that are running.

For example, we want a variable called subscriberIdx, which will have a different value in each running VU.

var subscriberVuOffset = subscribersPerVu * (__VU - 1);
common.subscriberIdx = subscriberVuOffset + (__ITER * common.numberOfRequest) % subscribersPerVu;

 Searching is suggesting that globalThis is scoped to each VU rather than being truly "global", so using this should be ok?

**Comment by joanlopez** [comment]
> It seems one way or the other we will have to rewrite the scripts to do something along the lines of 1 or 2.

Aha, you can try to find the way that requires the least amount of necessary changes in your project, but some will most likely needed, yeah.


> Searching is suggesting that globalThis is scoped to each VU rather than being truly "global", so using this should be ok?

Exactly, memory is not shared across VUs, as each VU operates in a separate JavaScript VM, thus `globalThis` is "global" at VU level.
But anyway, I'd recommend you to do a quick test of what you want/need before doing larger changes.

If you find any issue, please let us know. Thanks! 🙇🏻

**Comment by khamdocs** [comment]
The supplied workaround option 2 allowed the test to work. It required a moderate rewrite of the test and library, but I do not think there is much more to be done on this issue realistically so I am closing it as not planned. Thanks for the help.
