### ISSUE TITLE
k6 archive does not support --out flag for external metrics db

### ISSUE THREAD

**Issue by ts-sean-foley** [grafana/k6#4011]
### Brief summary

I am attempting to use operator to package a test with all required options. The documentation for `k6 archive` mentions that `metadata.json` will contain CLI flags as well as in-script options, and since we have been testing various external dbs for metrics as well as csv, I was expecting the archive command to help us get an archive with the --out uri/file which we were using with `k6 run`. Unfortunately the archive command fails when the --out flag is used, and reports that --out is an unknown flag. 

Is there a workaround for this issue? 

### k6 version

v0.48.0

### OS

manOS 14.7

### Docker version and image (if applicable)

n/a

### Steps to reproduce the problem

`k6 archive -O poc-full-flow-loki.tar --log-output=loki=https://REDACTED.grafana.net/loki/api/v1/push,label.qa=k6  --out csv=./results/test-output.csv ./src/scripts/poc-full-flow.js`

### Expected behaviour

Archive created with CLI flags placed in metadata of archive.

### Actual behaviour

`ERRO[0000] unknown flag: --out`

**Comment by ts-sean-foley** [comment]
Additionally, though `--log-output loki <loki uri>` was not rejected by the archive command, it does not appear that the log output flag was captured in the metadata.json.

**Comment by oleiade** [comment]
Hi @ts-sean-foley 👋🏻,

Thank you for taking the time to report this! 🙇🏻

From my perspective, this doesn't seem to be a bug but rather expected behavior. I wasn't part of the maintainers' team when the initial decisions around this were likely made, but I would intuitively assume that the reasoning was to keep the archive operation focused on creating a self-contained test artifact — essentially, "everything you need to be able to k6 run this later."

Including runtime details, such as where to send logs, seems outside the intended scope of the archive. In k6, the configuration for data output is handled at the point when the test artifact (test script or archive) is executed, either with k6 run or k6 cloud, not during the archive creation.

Of course, it's possible to see this differently, but this explanation might clarify why k6 behaves as it does in your scenario.

At the moment, I'm not aware of any workaround for this. However, @mstoykov might have deeper insights, and @yorugac might have suggestions for a workaround, especially since you mentioned this relates to your experience with the operator.

I hope this helps! Please feel free to reach out with any further questions. 🙇🏻

**Comment by mstoykov** [comment]
@oleiade is right as far as I know. While I have been here the longest at this point, I was not here in the original decisions to be made.

But the idea of the archive is to have a way to run the test with just moving a single artifact - the archive. 

Whether it will send logs somewhere or will output metrics to one or more outputs is not relevant to this.

Adding those also will require us to put even more sensitive data into the archive such as authorizations for the outputs. Also will mean that if you want to overwrite them the flags for this will need to figure this out.

This is also the first time I remember that someone has asked for this, so I don't really think we will try to support this.

AFAIK for the operator you will likely need to add *additional* stuff when running so that loki can figure out you are sending things from different servers. Even if you might not need it for sending only single series of logs from single server ... as it needed a few years ago.

This is kind of a requirement for most cases where you will be sending data from moer than one load generators either way.

**Comment by ts-sean-foley** [comment]
Thank upi @oleiade and @mstoykov  for your responses. I did further digging to try to understand how I could make the k6 loki output aware of the log destination specifics in a kubernetes/k6-operator scenario and learned of the arguments:  key in the resource spec for the operator CRD. I am sorry if I posed this question without thoroughly researching my options, but as I am sure you can understand, some of these minute details, especially around the loki output are pretty hard to find by googling, and often not in project documentation. I do understand the intention of archive command as you state it and can certainly agree with reasoning not to include/support some runtime arguments in the options object, but some of the documentation does imply that it was meant to capture the test, with it's arguments and options, so that a future run using that archive would be a repeat of the archived run invocation, so it is an issue of vague semantics. Thanks again.
