### ISSUE TITLE
To contribute on xk6-temporal extension

### ISSUE THREAD

**Issue by prmuthu** [grafana/k6#4088]
### Feature Description

Hi Team,

We have cloned xk6-temporal extension & customized it. We have used it in k6 script to start the temporal workflows for conducting loadtest. We would like to contribute the existing xk6-temporal repo and merge the same with main branch, so others also can use it.

@mstoykov 
As per our previous discussion ( https://github.com/grafana/k6/issues/4079#issuecomment-2505589862), you mentioned this is not being maintained by k6 team. But let me know how to contribute on existing xk6-temporal extension. Otherwise is it possible to create new repo and add it to k6 extension in grafana document? so others can use it. Please suggest me

**Comment by olegbespalov** [comment]
Hi @prmuthu 

>Otherwise is it possible to create new repo and add it to k6 extension in grafana document?

Like @mstoykov explained, we (k6 maintainers) don't own/maintain the repository https://github.com/temporalio/xk6-temporal, and since it's in an archived state that means that the original owner [temporalio](https://github.com/temporalio), doesn't maintain/accept new contributions too. 

If you want to continue work on that extension and planning to develop it, you could fork it (using the GitHub functionality). If by adding an extension in Grafana document, you mean adding it to the documentation page, previously I believe you just have to open a new pull request to a https://github.com/grafana/k6-docs. 

But nowadays, process could be a bit different, so maybe @grafana/k6-extensions could give some updates on that.
