### ISSUE TITLE
Support compression in websockets

### ISSUE THREAD

**Issue by wallenZhao2046** [grafana/k6#611]
I have used K6 in websocket performance test. While the content from server is compressed, and I got "�0E�e�!�56���j0&��v!�{�:�9�^�" printed in console. I used nodejs code to handle the same message from server. I got the right text.

So my question is how to decode compressed text in K6?

my K6 script is
```
socket.on('message', function (data) {
      console.log(typeof (data));
      console.log(data.length)
      if (data.length < 200) {
        // I got "�0E�e�!�56���j0&��v!�{�:�9�^�" in console
        console.log(data);
      }
      // I tried to decode it got "incorrect header check"
      let text = pako.inflate(data, { to: 'string' }); 
    }
```

If I used the following JS script, I got the correct text to inflate it to plain text.

```
ws.on('message', function (data) {

        console.log('-------- begin -------');
        // I got <Buffer 1f 8b 08 00 00 00 00 00 00 00 2d 8b 4b 0a 80 20 14 45 f7 72 c7 21 f9 1b e4 6e 34 1f 14 12 49 5e 47 d1 de 33 68 7a 3e 37 f6 8c 80 c4 b5 b7 4c 4c 68 3d in console
        console.log(data);
        console.log('-------- end -------');

        let text = pako.inflate(data, {
            to: 'string'
        });
        // msg is " msg: {"id":"btcusdt","subbed":"market.btcusdt.depth.step0","ts":1525243319443,"status":"ok"} "
        console.log('msg: ' + text);
    })
```

**Comment by na--** [comment]
I already answered in the [stackoverflow question](https://stackoverflow.com/questions/50128949/k6-k6-websocket-how-to-decode-compressed-text-in-k6/50129281#50129281), but I'll copy it here for posterity :smile: 

> As I mentioned in the [previous] [GitHub issue](https://github.com/loadimpact/k6/issues/594), it seems like pako's browserify version may have some issues when you specify `{ to: 'string' }` in the options. Instead you should be able to do something like this:
> ```
> let binText = pako.inflate(data);
> let strText = String.fromCharCode.apply(null, binText);
> console.log(strText);
> ```

Looking at this again, it seems like there is an official [RFC 7692](https://tools.ietf.org/html/rfc7692), which specifies websocket compression. So, if possible, I think we should actually natively support it directly in k6 so you don't have to rely on slow and external JS libraries like pako. Seems like it would be fairly straightforward, since the library we use for websockets seems to support compression: https://godoc.org/github.com/gorilla/websocket#Dialer.EnableCompression

**Comment by wallenZhao2046** [comment]
I have tried to update ws.go and rebuild to support compression. 
![image](https://user-images.githubusercontent.com/15209792/39513366-aef61e2e-4e26-11e8-9f09-f98f1ecb6a1b.png)

But got the same error message as below
![image](https://user-images.githubusercontent.com/15209792/39513516-3274630a-4e27-11e8-889a-9e729584702f.png)

**Comment by na--** [comment]
I slightly edited the title so we can use this issue for adding native websocket compression support in k6, without the need for external JS libraries. I also reopened the [old issue](https://github.com/loadimpact/k6/issues/594) so we can use it for tracking down the likely JS bug in k6, since it would be a good idea to find and fix it regardless of the native compression support.
