### ISSUE TITLE
Use AES/ECB/PKCS5Padding in k6

### ISSUE THREAD

**Issue by gushengyuan** [grafana/k6#637]
I want to use AES/ECB/PKCS5Padding to encrypt the payload data, and i tried to use several nodejs modules include crypto-js which used to convert to a standalone module using browserify, but it still does'nt work, 

Is there any one using AES/ECB/PKCS5Padding sucessfull in K6?

**Comment by na--** [comment]
Try using some encryption library meant for the browser, not for node.js. You usually can't use node libraries directly in k6, since they often depend on functions in node's standard library, though [browserify](http://browserify.org/) may help with that.

In general, even if the encryption using pure JavaScript works, it would probably be relatively slow and CPU-heavy. It's probably a good idea to expose some of Go's nice [encryption capabilities](https://golang.org/pkg/crypto/#pkg-subdirectories) in the JS runtime, like we currently do with the [hashing functions](https://docs.k6.io/docs/k6crypto). I've tagged this and edited the issue title slightly so we can use it to track the effort of adding fast "native" encryption in k6.

**Comment by gushengyuan** [comment]
That's sounds great, thanks @na-- 
By now, I use CryptoJS instead althought there are lots of issues using it in k6.
I'm very expecting a new k6 version to support more cryptographic algorithm

**Comment by oleiade** [comment]
We think the scope of this issue is addressed by the recent introduction of the [`k6/experimental/webcrypto`](https://k6.io/docs/javascript-api/k6-experimental/webcrypto/) module, which in its current state already offers support for AES encryption, using PKCS7 padding, as per the specification, which is, in theory, compatible with PKCS5 padding.

The Electronic Codebook (ECB) mode is generally considered insecure for most applications because it doesn't use an initialization vector (IV) and the same plaintext block will always produce the same ciphertext block. Due to its vulnerabilities, the WebCrypto API the module is based upon deliberately doesn't support ECB mode. Neither will k6, and if users need it, they might want to invest in [developing an extension to support it](https://k6.io/docs/extensions/).
