### ISSUE TITLE
Does k6 support golang as programming language?

### ISSUE THREAD

**Issue by HuiqianGithub** [grafana/k6#751]
Do we have plan to support golang as programming language? Currently it only support javascript.

**Comment by na--** [comment]
`yaegi` is a new project that could make this task much simpler:
- https://blog.containo.us/announcing-yaegi-263a1e2d070a
- https://github.com/containous/yaegi

**Comment by MStoykov** [comment]
WASM executors that might be used for running compiled wasm from golang:
* https://github.com/wasmerio/go-ext-wasm uses cgo - super fast but probably not a good idea
* https://github.com/go-interpreter/wagon - no cgo 
* https://github.com/perlin-network/life - no cgo

All three need investigation for both speed over goja and features that we will need . I mostly linked the cgo one for completeness, I am highly against using something using cgo , if it can be avoided.

**Comment by na--** [comment]
Ah, we probably should have mentioned it here, in case anyone is following the issue... While it's still not possible to write Go "scripts" in k6, it has been possible to write extensions in Go with xk6 since k6 v0.29.0:
- https://github.com/k6io/xk6
- https://k6.io/blog/extending-k6-with-xk6
- https://github.com/k6io/k6/blob/master/release%20notes/v0.29.0.md#support-for-go-extensions-1688

Moreover, there is already a basic xk6 extension with support for [yaegi](https://github.com/traefik/yaegi), i.e. "go scripting": https://github.com/dgzlopes/xk6-interpret

**Comment by jevonearth** [comment]
Has anyone made a basic test example written in go using xk6 that we can use for reference? 

"Technically Possible" is a great start to a story of protracted technical adventure. ;)

**Comment by na--** [comment]
Not that I know of, but you can examine some of the many xk6 extensions that already exist for inspiration: https://github.com/search?q=xk6&type=Repositories

While most xk6 extensions are meant to be imported from normal JavaScript-based k6 scripts (e.g. `import whatever from "k6/x/whatever"`) or, [since recently](https://github.com/k6io/k6/blob/master/release%20notes/v0.31.0.md#output-cleanup-and-extensions-1874), used as metric outputs, there's nothing stopping you from cramming your whole test logic in an "extension" and your whole k6 test script just being something like this:
```js
export * from "k6/x/myloadtest";
```

You can create and push metrics from your extensions (see https://github.com/dgzlopes/xk6-remote-write for example) and really do anything you might like with Go code :man_shrugging:

**Comment by dgzlopes** [comment]
Also, just to reference two basic examples:
- https://github.com/dgzlopes/xk6-say (the hello world of extensions)
- https://github.com/k6io/xk6-redis (the **useful** hello world of extensions) :smile: 

On the tutorial that @na-- referenced, there are instructions to build the Redis one from scratch.

**Comment by bandorko** [comment]
I've created an experimental tool that can be intresting in this topic. [k6-go](https://github.com/bandorko/k6-go)

**Comment by olegbespalov** [comment]
Closing as not planned.

There is another extension that allows you to write tests in golang https://github.com/szkiba/xk6-g0.

**Comment by krish7919** [comment]
> Some rationale related to this issue and other similar ones: https://k6.io/blog/why-k6-does-not-introduce-multiple-scripting-languages/

Link broken?
