### ISSUE TITLE
Stress test kafka stream application

### ISSUE THREAD

**Issue by B0bSapp** [grafana/k6#999]
In order to perform stress test for kafka-stream application I need to send avro messages to specified topic. So far I can not find such possibility, I think that this would be quite useful and dramatically increase functionality of this framework.

**Comment by zkutasi** [comment]
Is there any progress or info about this? Or is there a kafka-module one can use for this?

**Comment by mostafa** [comment]
Hi @B0bSapp and @zkutasi,

There's a PR for extending k6 with plugin support, that's going to add JS plugins in Go, so that anyone can extend k6 with their own Go module/plugin: https://github.com/loadimpact/k6/pull/1396
In the meantime, I've worked on a PoC, so that one can test Kafka:
https://github.com/mostafa/k6-plugin-kafka
I'd be happy to hear your feedback/suggestions about it.
BTW, also have a look at this PR:
https://github.com/mostafa/k6-plugin-kafka/pull/1

**Comment by codebien** [comment]
Closing as this is now already supported. As the previous comment mentions, [mostafa/xk6-kafka](https://github.com/mostafa/xk6-kafka) is an available extension and it has good support and maintenance.

Open an issue on the [dedicated board](https://github.com/mostafa/xk6-kafka/issues) for reporting bugs or requesting features.
